### ISSUE TITLE
Readme.rst: TEXT_ADDITIONAL_ATTRIBUTES

### ISSUE THREAD

**Issue by sthzg** [divio/djangocms-text-ckeditor#106]
I think on the very bottom of the README.MD the second line of the configuration example should be TEXT_ADDITIONAL_ATTRIBUTES instead of TEXT_ADDITIONAL_TAGS.

**Comment by ldgarcia** [comment]
You are right.

**Comment by yakky** [comment]
Thanks @sthzg @ldgarcia I totally missed that
