### ISSUE TITLE
enhance handling of child plugins editing

### ISSUE THREAD

**Issue by benzkji** [divio/djangocms-text-ckeditor#120]
having an option to better integrate custom plugins into the editor's html would be great. for example, "Link" is the only plugin allowed to have a `<a>` tag in the source

- the link plugin is very ok, but the rest seems to be doomed to use the old style icon_src and icon_alt concept
- the "name" field is automatically assumed to be the field that will hold the selected text

it would be nice if plugins could decide themselves how they want to be inserted into the editor. the needed attributes would be the existing, as the id with plugin_obj_877, but could be enhanced with own stuff. and fallback to the icon_src and icon_alt concept, if there is no enhancement for a particular plugin. 

and it would be nice, if the plugin dialog opening process is customizable too, as to set some default value, or do more advanced things.

**Comment by FinalAngel** [comment]
closed in favour of #285
