### ISSUE TITLE
Non-breaking space does no show up after saving the plugin

### ISSUE THREAD

**Issue by Wirzi** [divio/djangocms-text-ckeditor#131]
Hey
I using the github version of djangocms-text-ckeditor but someday all the new line breaks disappeared.

My settings for the plugin are: 

```
CKEDITOR_SETTINGS = {
	'language': '{{ language }}',
	'toolbar': 'HTMLField',
	'skin': 'moono',
}
```

In my editor window:
![bildschirmfoto 2014-05-28 um 14 27 19](https://cloud.githubusercontent.com/assets/1812094/3104194/a602132e-e663-11e3-82bf-ad97b38113f2.png)

In source code section:
![bildschirmfoto 2014-05-28 um 14 27 25](https://cloud.githubusercontent.com/assets/1812094/3104196/a602f30c-e663-11e3-86b9-8290d72bca4d.png)

In browser is no space:
![bildschirmfoto 2014-05-28 um 14 27 38](https://cloud.githubusercontent.com/assets/1812094/3104195/a6028b2e-e663-11e3-9599-05e87f7a484d.png)

But should be:
![bildschirmfoto 2014-05-28 um 14 28 04](https://cloud.githubusercontent.com/assets/1812094/3104213/dc74a87c-e663-11e3-8059-bcb218f6ef7c.png)

Any Idea why?

**Comment by FinalAngel** [comment]
closed in favour of #285
