### ISSUE TITLE
Possibly incorrect file path

### ISSUE THREAD

**Issue by andrewLab** [divio/djangocms-text-ckeditor#137]
master/djangocms_text_ckeditor/cms_plugins.py line: 64.

ckeditor_basepath = '{0}/ckeditor/'.format(settings.STATIC_URL)

In djangocms 3.0.2 the basepath appears incorrect already after installation. As STATIC_URL  = "/static/" and ckeditor_basepath = "/ckeditor/", the resulting ulr is "/static//ckeditor" is incorrect, thus editor is not loaded.
Suggest: 
ckeditor_basepath = '{0}ckeditor/'.format(settings.STATIC_URL)

**Comment by marksweb** [comment]
So I'm getting 404s from ckeditor's static files which are trying to access the skin files & config.js from `/static/ckeditor/` but the app includes the static files in `/static/djangocms_text_ckeditor/ckeditor/`.

I'd struggle to believe this issue has only happened to me as there's nothing special about our static setup - we just deploy out to an S3 bucket.

At the moment we've just manually copied `/djangocms_text_ckeditor/ckeditor/` and `/djangocms_text_ckeditor/ckeditor_plugins/` to `/static/` in order to avoid an issue. But what is the correct solution on this? I understand ckeditor itself lookup up the directory tree from where it is for a directory containing 'ckeditor' in order to identify it's home directory so I assume it's stopping 1 level too short. Is that right?

**Comment by FinalAngel** [comment]
What versions of django-cms and djangocms-text-ckeditor are you using? /cc @vxsx

**Comment by marksweb** [comment]
@FinalAngel @vxsx 

django-cms 3.0.16
djangocms-text-ckeditor 2.4.3

This project needs some work across the board to upgrade it's components, but it's been running for 2 years now & we've only just seen this issue.

**Comment by vxsx** [comment]
it looks to me like @marksweb issue is a bit different from what OP had, time passed, work was done etc.

@marksweb in 2.4.3 (and in latest master i believe) the basepath for ckeditor static comes from https://github.com/divio/djangocms-text-ckeditor/blob/fdb3349073c9d113ddd520f90482c682c5baad9d/djangocms_text_ckeditor/settings.py#L31 which seems to be correct, could you check what the value of `TEXT_CKEDITOR_BASE_PATH` is on your project?

in the frontend it's used in https://github.com/divio/djangocms-text-ckeditor/blob/fdb3349073c9d113ddd520f90482c682c5baad9d/djangocms_text_ckeditor/templates/cms/plugins/widgets/ckeditor.html#L8 so it also might be that block `extrahead` is overridden

**Comment by marksweb** [comment]
Thanks @vxsx.

`TEXT_CKEDITOR_BASE_PATH` appears to be set as it should be;
`/static/djangocms_text_ckeditor/ckeditor/`

Now that I've looked for that `ckeditor.html` template though I can see someone's provided us an override which is totally different to the package's own file. the `extrahead` block has a function that basically does a load of matching on resources to return `/static/ckeditor` paths;

```
{% block extrahead %}
    <script type="text/javascript">
        function CKEDITOR_GETURL(resource) {
            var match = resource.match(/^\/static\//);
            if (match) {
                {#            alert('STATIC  match ' + match + ' :: ' + resource)#}
                return resource;
            } else {
                {#            contents.css#}
                var match = resource.match(/contents\.css/);
                if (match) {
                    alert(' match ' + match + ' :: /static/ckeditor/' + resource)
                    return '/static/ckeditor/contents.css';
                }
                var match = resource.match(/^plugins/);
                if (match) {
                    {#                alert('plugins  match ' + match + ' :: ' + '/static/ckeditor/' + resource);#}
                    return '/static/ckeditor/' + resource;
                }
```

I'll get rid of this file & see how things are.

**Comment by FinalAngel** [comment]
@marksweb let us know :)

**Comment by marksweb** [comment]
I've stopped loading the template override & changed the names of the ckeditor dirs that we had in `/static/` and things are still working so it looks like it's properly using the `/static/djangocms_text_ckeditor/` path now.

Thanks for your time guys @FinalAngel @vxsx. Now it looks like some more template & JS overrides are preventing me from publishing in the 3.0.16 CMS release so I'll need to do some git commit research to see what client's didn't like about default CMS behaviour. Should be fun! :(

**Comment by FinalAngel** [comment]
you are very welcome @marksweb
