### ISSUE TITLE
Replace hacky <img ...> tags against something more descriptive

### ISSUE THREAD

**Issue by jrief** [divio/djangocms-text-ckeditor#143]
Raw text, as stored by djangocms-text-ckeditor in the database, contains image tags to hold information about links, images, snippets etc.

For instance, a link to an internal page is stored as:
``<img title="Link - Internal page" alt="Link" src="/static/cms/images/plugins/link.png" id="plugin_obj_67">``

this is ugly and quite inflexible. If for instance, we want to display a snippet as HTML, instead we would render an icon, representing “any snippet”.

Ckeditor encourages to use self-invented html tags for just that purpose. I therefore would suggest to replace these hacky image tags against a special HTML tag defining child plugins. As this special tag, I would use ``<cmsplugin plugin_obj="67" plugin_type="Link">Internal page</cmsplugin>`` (the attribute ``plugin_type="Link"`` may be omitted, since it can be determined by the plugin id, here 67).

The big advantage using this syntax, is, that parsing its content is much simpler. Instead of using [an error prone regular expressions](https://github.com/divio/djangocms-text-ckeditor/blob/master/djangocms_text_ckeditor/models.py#L70), any ordinary DOM parser will do the job. Additionally, the HTML content, as loaded from the DB-table ``djangocms_text_ckeditor_text``, can be rendered directly, since the wrapping HTML tags ``<cmsplugin ...></cmsplugin>`` are silently ignored by browsers. Therefore, the content of snippets will be rendered inside Ckeditor's working area. Double clicking on such a snippet, would open the Snippet-Editor.

Apart from that, such a solution would be much cleaner than the current one. I really dislike the way values from child plugins, currently are twisted to be storable in such an abused image tag.

Since I have some experience with the API of Ckeditor, I could rewrite this. Please vote for or against this proposal.

Jacob

**Comment by FinalAngel** [comment]
closed in favour of #285
