### ISSUE TITLE
Installation instructions

### ISSUE THREAD

**Issue by mmarzantowicz** [divio/djangocms-text-ckeditor#146]
Why there is an instruction to place `djangocms_text_ckeditor` before `cms` entry in `INSTALLED_APPS` setting? Is there any technical reason for that requirement? One thing that comes to my mind is template overriding but is it for that reason?

**Comment by FinalAngel** [comment]
@yakky would you know the exact reason?

**Comment by FinalAngel** [comment]
order does not matter anymore
