### ISSUE TITLE
Question/Feature: Haystack support

### ISSUE THREAD

**Issue by sthzg** [divio/djangocms-text-ckeditor#160]
Is it possible / are there examples how to integrate content provided in ``djangocms-text-ckeditor`` plugin instances to the Haystack search index? I googled a bit but had no luck. If there are practices on how to achieve this (maybe related to ``aldryn_search``) I think it would help some developers to mention it in the docs.

**Comment by marksweb** [comment]
@sthzg Would you be able to share your search items template? The default `aldryn_search` templates aren't that great, I just end up with a list of 'none' list items.
