### ISSUE TITLE
CkEditor plugins , how to add more ?

### ISSUE THREAD

**Issue by petzlux** [divio/djangocms-text-ckeditor#182]
I am trying to integrate the following CKEditor plugin: 
http://ckeditor.com/addon/codesnippet

The fork with the plugin added can be found here:
https://github.com/petzlux/djangocms-text-ckeditor

Now I am a bit at a loss as to how to integrate it into my DjangoCMS installation? 

I tried simply adding the plugin int the config of my project as follows:

```
CKEDITOR_SETTINGS = {
    'language': '{{ language }}',
    'toolbar': 'CMS',
    'skin': 'moono',
    'extraPlugins': 'codesnippet',
}
```

But that doesnt add the functionality in the toolbar. What else needs to be done ?

**Comment by creimers** [comment]
I got it to work like this:

```
CKEDITOR_SETTINGS = {
  ...
  'extraPlugins': 'codesnippet',
  'toolbar_CMS': [
    ...
    ['CodeSnippet', ]
    ...
  ]
}
```

Codesnippet's dependencies appear to be [widget](http://ckeditor.com/addon/widget) and [lineutils](http://ckeditor.com/addon/lineutils), which also (just like codesnippet) have to be copied to ckeditor's plugin dir (``djangocms_text_ckeditor/ckeditor/plugins``).
