### ISSUE TITLE
diango 1.6 ckeditor loading multiple times - upgrade?

### ISSUE THREAD

**Issue by giorg** [divio/djangocms-text-ckeditor#192]
Hi,

using Django 1.6.5 and djangocms-text-ckeditor 2.1.6 I see the ckeditor is loading multiple times, once per textarea I defined in my model. This makes the loading of the page (admin side) very slow. I've read in the doc of ckeditor this should be solved with version 3 of ckeditor, is it a bug or should I upgrade the ckeditor? In this case, how to?

thanks  a lot

**Comment by yakky** [comment]
Closing due to no feedback
