### ISSUE TITLE
Permissions not created/adapted when switching from cms.plugins.text

### ISSUE THREAD

**Issue by Pankrat** [divio/djangocms-text-ckeditor#21]
We followed the README to upgrade from cms.plugins.text.  

Afterwards our editors couldn't access text plugins anymore and there was no permission for ckeditor - probably because the migration was faked?

We worked around that by manually changing `app_label` in `django_content_type` from *text* to *djangocms_text_ckeditor*.

Not sure if there is a better way to do that. If there isn't, maybe this could be documented.

Thanks

**Comment by FinalAngel** [comment]
Clsoing in favour of #78
