### ISSUE TITLE
Canceling editing a link plugin leads to persistance of plugin contents when editing other link plugins

### ISSUE THREAD

**Issue by Moini** [divio/djangocms-text-ckeditor#218]
Might be related to #116

1.) Make two different plugin links (those with img tag) with the editor (one to 'http://foo.com', one to 'http://bar.com')
2.) Right-click on foo.com link, Choose Edit Plugin
3.) Cancel
4.) Right-click on bar.com link. Choose Edit Plugin
5.) Now the editing dialog shows (and would save!) the contents of the last opened dialog foo.com.

This does not happen if you choose 'Save' in 3.)

The wrong contents is kept as long as the editor window is open, until any link plugin is saved.

This is really very nasty, if you have translators who only need to edit plugins. You probably won't even notice if you only create them...

**Comment by Moini** [comment]
More info:
I'm using FF 35 on LM 17 (Mozilla Firefox for Linux Mint 1.0 is the second label in 'About')
Using web developer toolbar, caching deactivated completely with it. 
But still I sometimes have issues with cached js in iframes (don't know if there's a relation).

This does not happen in Chromium for me, and a colleague only sees the old form flashing shortly in IE and also in FF (didn't mention version numbers) on Win7.

So probably this problem concerns less people than I feared :) and might even be related to just my own specific setup.

**Comment by Moini** [comment]
This is a setup which works:
> Firefox version is 35.0 / Win7
> IE is 11.0.9600.17501 / Win7

**Comment by jrief** [comment]
AFAIK this is caused by the usage of MPTT for managing plugins.
DjangoCMS > 3.1 uses treebeard instead of MPTT and there this has been fixed.

**Comment by Moini** [comment]
We are running 3.06. 
So I'll wait for 3.1 and use Chromium in the meantime for this kind of task ;)
Thank you very much!
