### ISSUE TITLE
More problems with plugin links

### ISSUE THREAD

**Issue by Moini** [divio/djangocms-text-ckeditor#220]
Hi,

editing plugin links behaves weird for us, there are several problems which occur:

1.) Right-click on a plugin-link in the editor, choose 'Edit Plugin', change text of the link, save -> Link is duplicated on the page. This does not seem to occur if you double-click to select the whole link first.

2.) Changing the text of the link in the editor directly does not have any effect - it looks correct in the editor, it looks correct in the draft, but it's back to the previous state when published.

Currently running django-cms 3.09. 
Do these work correctly with the "Ent" (treebeard) in your development version?
(and did you receive the security related mail I sent two days ago?)

**Comment by FinalAngel** [comment]
closed in favour of #285
