### ISSUE TITLE
Wishlist: Scroll to correct point in html when toggling to source mode

### ISSUE THREAD

**Issue by Moini** [divio/djangocms-text-ckeditor#223]
For very long texts, it's difficult to find the correct place to continue editing when toggling to source mode. 

If it would automatically scroll to the place where the cursor currently is in the 'normal' editor, this would make things a lot easier.

**Comment by yakky** [comment]
I think this is out of the scope of this plugin. Shipped ckeditor configuration can be easily extended with standard ckeditor addons.
I don't know if such an addon exists, though

**Comment by doctormo** [comment]
Since the ckeditor is shipped with-in the plugin, should the plugin not be in control of the most ideal set of ckeditor plugins? We've noticed the very vanilla nature of the editor and how difficult it is to extend. Could the plugin provide some mechanisms to make this easier?

**Comment by yakky** [comment]
enabling standard ckeditor addons is as easy as extending CKEDITOR_SETTINGS declaring the new addons and put the addon files in ``static/djangocms_text_ckeditor/ckeditor/plugins/`` in any application available in the project
Supporting every sensible ckeditor addon would render this plugin quite messy and burdensome to support
