### ISSUE TITLE
Wishlist: Syntax highlighting for html in source mode

### ISSUE THREAD

**Issue by Moini** [divio/djangocms-text-ckeditor#224]
To make editing the source html easier, it would be nice if it used some syntax highlighting.

**Comment by yakky** [comment]
There are ckeditor addons that does this (like http://ckeditor.com/addon/syntaxhighlight) and you can easily add them to the project configuration

**Comment by Moini** [comment]
Thank you, yakky!

**Comment by Moini** [comment]
(although I think this plugin does something different - I meant something to ease editing the html source, but this plugin seems to add color to the saved page).
