### ISSUE TITLE
No SpellChecker implemented

### ISSUE THREAD

**Issue by quiqueporta** [divio/djangocms-text-ckeditor#226]
Hi! i'm trying to add SpellChecker to the widget but seems is not implemented.

``` python
CKEDITOR_SETTINGS_MODEL_1 = {
    'toolbar_HTMLField': [
        ['Undo', 'Redo'],
        ['SpellChecker'],
    ],
 ]
```

**Comment by yakky** [comment]
Spellchecker ckeditor addon is not included.
You must add to you project by downloading/installing as any other ckeditor addon
