### ISSUE TITLE
Do not wrap ImagePlugin into paragraph

### ISSUE THREAD

**Issue by satyrius** [divio/djangocms-text-ckeditor#230]
Editor wraps text into paragraphs automatically, and it's great. But I don't want it to wrap ImagePlugin into `<p/>` because it has its own render template which add all I need. How to configure custom behaviour for auto-wrapping?

**Comment by yakky** [comment]
You can select the "div" element from the dropdown menu before or after inserting an image plugin.
This is actually a ckeditor setting anyway, not related to the django CMS plugin
