### ISSUE TITLE
Modal fills screen

### ISSUE THREAD

**Issue by zsoobhan** [divio/djangocms-text-ckeditor#232]
When I double click to edit a text box, the ckeditor modal pops up as intended however it fills the screen completely to the point where it is unusable. i.e. the save buttons are off the window and I have to reduce my font size to even see the edge. Any ideas? Perhaps something I can add to ```CKEDITOR_SETTINGS```?
![django_ckeditor_bug](https://cloud.githubusercontent.com/assets/6103879/6916109/6bae7dbe-d791-11e4-84cc-0767d93f97ce.png)

**Comment by zsoobhan** [comment]
The issue was being caused by the menu being shown in the base template. 

```
<ul> {% show_menu 0 1 100 100 %} </ul>
```

**Comment by bxm156** [comment]
@zsoobhan  I have encountered this issue as well, How did you fix it ?

**Comment by zsoobhan** [comment]
@bxm156 this happened so long ago and my comment is somehow less than helpful. I no longer have access to the code base but if memory serves me right, the problem was with the `show_menu` flag being used twice. Once in the `base_template` and once in the inherited one.
Suggestion:
Try removing the `show_menu` flag in all the templates being used and see if that fixes the issue. 
If that works, please document it in this thread (better than I did).
