### ISSUE TITLE
Provide drag&drop image saving for HTMLField

### ISSUE THREAD

**Issue by brigantino2** [divio/djangocms-text-ckeditor#233]
In the docs you read 

> Drag & Drop Images
> In IE and Firefox based browsers it is possible to drag and drop a picture into the text editor. This image is base64 encoded and lives in the 'src' attribute as a 'data' tag.
> We detect this images, encode them and convert them to picture plugins

That's a great feature, but as far as I've seen, if I'm not mistaken, this works only with plugins, that means, if you have a text area in your plugin, you will be able to save dragged&dropped images.
On the other hand this feature is not provided for ```HTMLField```, so if you want to use that in your models, you'll have the same ckeditor window, but saving drag&drop images won't work. It would be nice to have ```extract_images``` be involved with ```HTMLField```.

**Comment by yakky** [comment]
Given how currently the image inclusion works in this plugin (i.e.: by using plugins) it's not currently possible to implement drag and drop in HTMLField.
This will require an entirely different strategy to support images in HTMLField

**Comment by FinalAngel** [comment]
closed in favour of #285
