### ISSUE TITLE
Path to plugin.js seems incorrect

### ISSUE THREAD

**Issue by marksweb** [divio/djangocms-text-ckeditor#234]
I've just noticed the text plugin failing to load locally after it couldn't find `plugin.js`.

On inspecting the path locally I've got `static/djangocms_text_ckeditor/ckeditor_plugins/cmsplugins/plugin.js`

But in [cms.ckeditor.js#L60](https://github.com/divio/djangocms-text-ckeditor/blob/2.4.3/djangocms_text_ckeditor/static/djangocms_text_ckeditor/js/cms.ckeditor.js#L60) the path seems to miss out the djangocms_text_ckeditor directory; 

```js
CKEDITOR.plugins.addExternal('cmsplugins', settings.static_url + '/ckeditor_plugins/cmsplugins/');
```

Should that not be;
```js
CKEDITOR.plugins.addExternal('cmsplugins', settings.static_url + '/djangocms_text_ckeditor/ckeditor_plugins/cmsplugins/');
```

**Comment by yakky** [comment]
Path should be correct (``settings.static_url`` is set here https://github.com/divio/djangocms-text-ckeditor/blob/2.4.3/djangocms_text_ckeditor/templates/cms/plugins/widgets/ckeditor.html#L25 and includes ``djangocms_text_ckeditor`` part)
Have you recently updated from older version?

**Comment by marksweb** [comment]
Don't think I've updated recently, and it only seemed to happen locally so maybe just an odd scenario on my machine I guess. If I see it on a remote machine I'll come back! Thanks @yakky
