### ISSUE TITLE
Problem with inline admin integration

### ISSUE THREAD

**Issue by nicolas8448** [divio/djangocms-text-ckeditor#237]
I seem to have a problem with the HTMLField inside a custom plugin with Inlines created inside Django CMS.

When I enter inside the modal in the front-end to edit the plugin, all the inlines with HTMLField works, but when I press the add-row button, the next inline starts with a Textfield instead of the Ckeditor field.

The function use to call the CKeditor remains like this : initCMSCKEditorid_slide_image___prefix___text(); inside the new Inline created.

**Comment by creimers** [comment]
+1

**Comment by rikaa** [comment]
+1

**Comment by FinalAngel** [comment]
sorry for the late delay @nicolas8448, would you be able to provide a screenshot so we understand the problem better?

**Comment by FinalAngel** [comment]
please re-open if its still relevant to you. A screenshot or screencast would be welcome to understand the problem.
