### ISSUE TITLE
CMS Plugins menu does not honor plugin_modules or plugin_labels CMS settings

### ISSUE THREAD

**Issue by jbazik** [divio/djangocms-text-ckeditor#238]
Django-cms allows one to alter the menu display of plugins both by controlling the way they are grouped and the way they are named.  These are the plugin_modules and plugin_labels settings in CMS_PLACEHOLDER_CONF.  The ckeditor "CMS Plugins" menu ignores these settings.  For a more consistent experience for users, it would help if this menu matched the one offered by the cms itself.

Grouping and naming is hardcoded in templates/cms/plugins/widgets/ckeditor.html using
  {% regroup installed_plugins by module as module_list %}
and naming them {{ plugin.name }}.

I'd offer a patch, but my sense is that there's a bit too much going on in the template, and this logic needs to move into the view.

**Comment by yakky** [comment]
@jbazik please check above PR

**Comment by yakky** [comment]
Ping @jbazik any feedback on #243?

**Comment by jbazik** [comment]
> Ping @jbazik any feedback on #243?

Sorry - very busy week.  Will test and respond shortly.

John

**Comment by yakky** [comment]
@jbazik thanks a lot!

**Comment by jbazik** [comment]
Looks good.  I'll test it tomorrow when I'm back at work.

John

**Comment by jbazik** [comment]
Fixed!  Thanks!

John

**Comment by yakky** [comment]
Thanks for reporting and support
