### ISSUE TITLE
img tags loose their src attribute on save

### ISSUE THREAD

**Issue by stefanfoulis** [divio/djangocms-text-ckeditor#244]
The src attribute seems to be removed on manually added ``img`` tags by the backend.
E.g when adding
```
<img src="/static/my-logo.svg">
```
in the "source" mode of the ckeditor.

**Comment by yakky** [comment]
@stefanfoulis which html5lib version in the virtualenv?

**Comment by grzegorzbialy** [comment]
@yakky I ran into this today. It looks like src attribute is cleared with html5lib 0.9999/1.0b5 and 0.99999/1.0b6.
Downgrading to 0.999 resolves issue.

**Comment by yakky** [comment]
Newer versions of djangocms_text_ckeditor have a versioned dependency on html5lib for this very reason https://github.com/divio/djangocms-text-ckeditor/blob/master/setup.py#L9
