### ISSUE TITLE
2.5.1 does not migrate on django 1.7

### ISSUE THREAD

**Issue by benzkji** [divio/djangocms-text-ckeditor#247]
I'm still investigating, but it seems to me that I still need

```
MIGRATION_MODULES = {
    'djangocms_text_ckeditor': 'djangocms_text_ckeditor.migrations_django',
}
```

for djangocms-text-ckeditor to work with django 1.7.

I looked at the installed package (did pip install djangocms-text-ckeditor today, and it installed 2.5.1), and there are three directories: migrations, migrations_django and south_migrations. the "migrations" folder looks like containing south migrations? could be related to this issue (pip, wheel?): https://github.com/django-tastypie/django-tastypie/issues/1231 ? as I dont see the "migrations_django" folder here on github???

the error message I get when trying to migrate without MIGRATION_MODULES set is specialy disturbing:
```
Applying djangocms_text_ckeditor.0001_initial...Traceback (most recent call last):
...
django.core.exceptions.ImproperlyConfigured: Application labels aren't unique, duplicates: djangocms_text_ckeditor
```

**Comment by yakky** [comment]
Apparently some error in the packaging phase.
2.5.2 has been released to fix this

**Comment by benzkji** [comment]
thx. FAST!
