### ISSUE TITLE
djangocms-link instances loose "name" attribute in popup dialog after adding another link instance

### ISSUE THREAD

**Issue by benzkji** [divio/djangocms-text-ckeditor#249]
to reproduce:
- open a ckeditor instance with an existing djangocms-link
- insert a new djangocms-link instance (select some text, then choose "Link" from plugin dropdown).
- double click the existing link. it's name field has the value of the existing one
- if the new link is inserted without any text selected, all links will have blank "name" fields.

versions:
djangocms-text-ckeditor==2.5.2 with custom link plugin (that has a name field)
and also on an older one:
djangocms-link==1.3.4
djangocms-text-ckeditor>=2.1.4

**Comment by FinalAngel** [comment]
closed in favour of #285
