### ISSUE TITLE
TEXT_HTML_SANITIZE don't work for onclick attribute

### ISSUE THREAD

**Issue by dPeS** [divio/djangocms-text-ckeditor#250]
Hi all,

I have a contact form placed in ckeditor plugin which is send via ajax call from onclick attribute. I've found out that this attribute is still stripped out with TEXT_HTML_SANITIZE = False which is very confusing.

also tried to TEXT_ADDITIONAL_ATTRIBUTES = ('onclick,) without luck... 
djangocms-text-ckeditor (2.3.0)

Regards

**Comment by ojii** [comment]
The offending line seems to be https://github.com/divio/djangocms-text-ckeditor/blob/master/djangocms_text_ckeditor/html.py#L18, if it's set to ``False`` it should probably just return the input.

In a related note, I feel like the docs about this setting should make the dangers of this setting more explicit.

**Comment by yakky** [comment]
@dPeS You can configure the sanitiser https://github.com/divio/djangocms-text-ckeditor#configurable-sanitizer by allowing specific attributes to be preserved.

@ojii while I tend to agree with you, sanitisation is a standard term for this operation. We migth add big fat warnings in the relevant section of the documentation to warn against disabling it, though

**Comment by dPeS** [comment]
"also tried to TEXT_ADDITIONAL_ATTRIBUTES = ('onclick,) without luck... "

**Comment by yakky** [comment]
@dPeS Did you re-enable ``TEXT_HTML_SANITIZE``? Still on version 2.3?

**Comment by dPeS** [comment]
yes a was trying >one< option in time, could redo tests if You want

**Comment by yakky** [comment]
If it does not work with 2.5.2, it's definitely a bug that needs to be addressed

**Comment by dPeS** [comment]
ok, I will test it on 2.5.2 today and let You know

**Comment by dPeS** [comment]
tested on 2.5.2 with:

TEXT_ADDITIONAL_ATTRIBUTES = ('onclick',)

still the same, attribute is removed

**Comment by yakky** [comment]
@dPeS thanks for your report and checks. Which version of html5lib is installed?

**Comment by dPeS** [comment]
pip install ==2.5.2 forced html5lib 0.999 to install, but before with 2.3.0 I had 1.0b1 installed

**Comment by FinalAngel** [comment]
@yakky any progress here?

**Comment by dPeS** [comment]
for me is not relevant anymore - found a workaround, thanks d.
