### ISSUE TITLE
Allow data attributes

### ISSUE THREAD

**Issue by FinalAngel** [divio/djangocms-text-ckeditor#251]
need to proper format ``CKEDITOR.config.allowedContent = true;``

**Comment by astagi** [comment]
@FinalAngel working on.. can you assign this issue to me?

**Comment by FinalAngel** [comment]
I apparently can, but I'll keep it in mind @astagi - awesome!
It also looks like that it is connected to html5lib used in cms

**Comment by astagi** [comment]
@FinalAngel no problem :) yes, I override the default behaviour of html5lib, now you can write some custom classes to tell sanitisation process how to treat certain attributes (e.g. data attributes https://github.com/astagi/djangocms-text-ckeditor/blob/d4547d1952af429153c1853db8dd1446557fa0b3/djangocms_text_ckeditor/attribute_parsers.py). I get some strange errors on Travis using Django 1.4 + CMS 3.0 though.
