### ISSUE TITLE
relation "djangocms_text_ckeditor_text" does not exist LINE 1: ...r_id", "djangocms_text_ckeditor_text"."body" FROM "djangocms...

### ISSUE THREAD

**Issue by ShivangPandey** [divio/djangocms-text-ckeditor#265]
I am new to this django framework and currently i am exploring this framework.
When i tried to implement the django cms text plugin to my existing project, it shows the error when i tried to use the plugin. If i am not using the installed plugin then everything works fine but using the text plugin causes the issues. I have tried all the above mentioned solutions but none of them solved the problem. Can anyone guide me thats what may be the possible issue in this.

**Comment by ShivangPandey** [comment]
this issue is same as of tickect number #112 and i have tried all the solutions given in that issue but it is not resolving the issue.

**Comment by yakky** [comment]
Are you following the django-cms tutorial? http://django-cms.readthedocs.org/en/develop/introduction/index.html

**Comment by ShivangPandey** [comment]
yaa i implemented it buy following the tutorial it self. And followed each and every step mentioned

**Comment by ShivangPandey** [comment]
i also followed the solution mentioned in ticket number #13 and still the error is same

**Comment by ShivangPandey** [comment]
Yeah I resolved this issue....the main thing was that i was using django 1.7 and by default it was trying to run south migrations so in order to resolve that i just added this to MIGRATION_MODULE  under the settings.py:
'djangocms_text_ckeditor': 'djangocms_text_ckeditor.migrations_django',

This will explicitly tell the framework to run migrations instead of south migrations.
Since the main issue was djangocms_text_ckeditor's table was not getting created under the db

**Comment by yakky** [comment]
This should not be needed with latest djangocms_text_ckeditor. Which versiondo you have installed?

**Comment by ShivangPandey** [comment]
djangocms-text-ckeditor==2.6.0
I guess this is the latest version

**Comment by yakky** [comment]
djangocms-text-ckeditor==2.6.0 is the latest, but it does not have ``djangocms_text_ckeditor.migrations_django`` module, and it should not require any ``MIGRATION_MODULE``
