### ISSUE TITLE
Smarter approach of white-listing additional tags and attributes.

### ISSUE THREAD

**Issue by barseghyanartur** [divio/djangocms-text-ckeditor#266]
At the moment, additional tags and attributes are set separately:

    TEXT_ADDITIONAL_TAGS = ('iframe', 'img')
    TEXT_ADDITIONAL_ATTRIBUTES = ('src', 'scrolling', 'allowfullscreen',
                                  'frameborder', 'width', 'height',)

It would be much better to have something like this instead:

    TEXT_ADDITIONAL_TAGS = {
        'iframe': ('src', 'scrolling', 'allowfullscreen', 'frameborder', 
                   'width', 'height',),
        'img': ('alt',)
    }

In that way, 'width' won't be a valid attribute for 'img', but will be for 'iframe'.

`TEXT_ADDITIONAL_ATTRIBUTES` would then become obsolete.

**Comment by yakky** [comment]
@barseghyanartur it'd be a nice feature, but I don't think html5lib (which we use for checking attributes and tags) supports this syntax

**Comment by barseghyanartur** [comment]
@yakky:

`bleach` is based on `html5lib` too but it does have that syntax. I first used it about 5 years ago and then it was rock-solid. I beleive it changed only to better since then.

- http://bleach.readthedocs.org/en/latest/clean.html#attribute-whitelist

So, I'd say, use `bleach` for stripping out the unwanted tags/attributes.

**Comment by yakky** [comment]
@barseghyanartur it's an interesting option. Migrating to bleach will require some planning, though.

**Comment by FinalAngel** [comment]
@barseghyanartur or @yakky I'd welcome a PR on migrating to bleach eventually. For now I'll close this.
