### ISSUE TITLE
fontawesome tag disappear when I edit the text

### ISSUE THREAD

**Issue by stevandoh** [divio/djangocms-text-ckeditor#270]
HI
 I ve been struggling to add fontawesome to my text . I understand that there is an issue with empty i tag . I ve try to solve the issue by adding this line to the config.js : config.protectedSource.push(/<i[^>]*><\/i>/g); without success . Any help ll be welcomed

Thanks in advance

**Comment by FinalAngel** [comment]
This would probably a better question for the ckeditor community @stevandoh as we do not have a deep understanding of the editors internal mechanics. Did you progress so far?
