### ISSUE TITLE
Link copy-pasting can lead to data loss

### ISSUE THREAD

**Issue by FinalAngel** [divio/djangocms-text-ckeditor#271]
When copy-pasting links a reference to the plugin is pasted instead of a copy of the plugin. Which causes issues in the following cases:

* Copying a link in a Text field (With Ctrl-C) and pasting it somewhere else and then changing it (either its title or the target) will also change the original link
* Copying the contents of a Text instance (again by selecting the text in the WYSIWYG and Ctrl-C) with links to another Text instance and then deleting the first Text instance will remove all the links in the second Text instance, which is very dangerous

reported by @sephii https://github.com/divio/django-cms/issues/4620#issuecomment-151558948

**Comment by yakky** [comment]
Can we hijack the copy action in the javascript. It's the only way we can try to fix this

**Comment by yakky** [comment]
(sorry, closed by miostake)

**Comment by FinalAngel** [comment]
hehe no problem @yakky we would probably have to make sure the rendering engine actually copies it back correctly. I think thats the cleanup magic by ckeditor

**Comment by FinalAngel** [comment]
closed in favour of #285
