### ISSUE TITLE
Image alignment with cmsplugin_filer_image

### ISSUE THREAD

**Issue by rafadev** [divio/djangocms-text-ckeditor#274]
I'm using the integration with the cmsplugin_filer_image plugin, and what I can't find the way around is how to float the selected image inside CKEditor itself. What happens is, on the filer plugin, I can select align, and choose left, right, or center. However inside the editor the image is inserted as a normal image, without any specific classes, so I can't display as floating. On the final rendered template, it is floated because it gets a " filer_image left/right/center" class. Is there a way around this?

Here's an example of how choosing left looks on the editor:
![selection_078](https://cloud.githubusercontent.com/assets/757742/11023421/9db2354c-8657-11e5-9a6e-c292c92e2d16.png)

I'm posting this here instead of Filer because I figured it has to do with the integration and not with Filer itself. Thank you!!

**Comment by FinalAngel** [comment]
closed in favour of #285
