### ISSUE TITLE
incorrect doc for "Adding plugins to the "CMS Plugins" dropdown" in README.rst

### ISSUE THREAD

**Issue by alexandrenorman** [divio/djangocms-text-ckeditor#288]
The link given in documentation is outdated:

    Adding plugins to the "CMS Plugins" dropdown
    --------------------------------------------

    If you have another plugin that you want to use inside texts you can make them appear in 
    the dropdown by making them text_enabled.
    Check in `django-cms doc`_ how to do this.

    .. _django-cms doc: http://django-cms.readthedocs.org/en/develop/extending_cms/custom_plugins.html#text-enabled

Therefor I am not able to get other plugins (esp. filer) working with djcms-3.2 and last djangocms-text-ckeditor

**Comment by FinalAngel** [comment]
@alexandrenorman thank you very much for the report. Would you be able to open a pull request addressing the issue?

**Comment by yakky** [comment]
Fixed in #290 289
