### ISSUE TITLE
CSRFMiddlewaretoken

### ISSUE THREAD

**Issue by putvande** [divio/djangocms-text-ckeditor#291]
Hi,

I'm currently running into an issue whereby djangocms_text_ckeditor doesn't send the CSRFMiddlewaretoken when adding a plugin from the dropdown menu in Django CMS.
I get a "403 Forbidden CSRF token missing or incorrect." error. When digging in the code, it seems that the CSRFMiddlewaretoken is not send.

I'm running Django 1.7.11 and Django CMS 3.1.4 with djangocms_text_ckeditor 2.8.0. When I downgrade djangocms_text_ckeditor to 2.7.0 this problem goes away.

Have you heard about this before and can this be resolved without having to downgrade?

Thanks

**Comment by FinalAngel** [comment]
@putvande thank you for your feedback, this is documented in the readme:

``For django CMS 3.0 and 3.1 use djangocms-text-ckeditor <= 2.7 (e.g.: version 2.7.0).``

ckeditor 2.8.0 is for django-cms >= 3.2.0
