### ISSUE TITLE
Calling template tag inside djangocms text ckeditor

### ISSUE THREAD

**Issue by rgcarrasqueira** [divio/djangocms-text-ckeditor#294]
Hi!

I would like to know if is it possible to call a template tag inside the text ckeditor, for example:

{% static "mypath/images/next.png" %} inside the text

Thanks

**Comment by czpython** [comment]
Hello,
Currently it is not possible.
There's no planned effort to make this possible as it opens some security concerns.

**Comment by frnhr** [comment]
@rgcarrasqueira 
Maybe give this a try: https://github.com/frnhr/djangocms_renderit

Disclaimers:
 - I made it
 - last tested on DjangoCMS 3.1
 - only use if security is not a concern (i.e. all your users are trustworthy)
 - only use if security is not a concern, I make no guarantees with regards to safety
