### ISSUE TITLE
Problems to open plugins window inside ckeditor when my site is running with a CDN like CloudFront

### ISSUE THREAD

**Issue by rgcarrasqueira** [divio/djangocms-text-ckeditor#295]
Hi Folks!

I'm trying to use django-cms and djangocms-text-ckeditor running on my site and all JS and CSS files running on a CDN like AWS Cloudfront. So, I'm facing problems like bellow when I'm trying to call the plugin window inside the ckeditor dialog window already open, when the window freeze an none was opened and I catch this error at my JS console:

TypeError: CMS.$(...).on is not a function
https://d3ce9j2o7f76t5.cloudfront.net/djangocms_text_ckeditor/ckeditor_plugins/cmsplugins/plugin.js?t=F969
Line 82

Any one has an idea on how to deal with that?

Thanks

Rogério Carrasqueira

**Comment by einarf** [comment]
Had a similar issue related to this when using master branch, but 2.9.0 resolved it.
