### ISSUE TITLE
Unwanted whitespace between anchor and punctuation mark

### ISSUE THREAD

**Issue by creimers** [divio/djangocms-text-ckeditor#296]
Using the TextPlugin, I'm getting this unwanted whitespace between an anchor (filer link plugin) and a trailing punctuation mark. 
<img width="249" alt="bildschirmfoto 2016-01-18 um 07 26 15" src="https://cloud.githubusercontent.com/assets/6090492/12384662/c8c31f50-bdb4-11e5-803b-5548b23b653a.png">

In the developer tools, I can see that there is some kind of strange newline before the comma. If I go on and delete the whitespace there, it disappears of course. 
<img width="497" alt="bildschirmfoto 2016-01-18 um 07 17 00" src="https://cloud.githubusercontent.com/assets/6090492/12384669/da0c14ec-bdb4-11e5-8f82-04f24bea52ec.png">

I can rule out styling, as it is persistent with all css excluded:
<img width="236" alt="bildschirmfoto 2016-01-18 um 07 18 34" src="https://cloud.githubusercontent.com/assets/6090492/12384653/b45d1a66-bdb4-11e5-9ddd-63fe01e0febc.png">

I have observed this with both commas and full stops in djangocms 3.1 (djangocms-text-editor==2.4.3) and 3.2 (djangocms-text-editor==2.8.1)

Any ideas on how to get rid of that whitespace?

**Comment by nilssolanki** [comment]
We have the same issue between links and normal text (without punctuation marks afterwards).

**Comment by vxsx** [comment]
This is the issue with the link plugin you're using. If the template for the link plugin has whitespace at the end of the file (or newline at the end of file) - it would render as a space, not really an issue with the text plugin. I believe at this point filer link, djangocms-link and aldryn-bootstrap3 link plugins are fixed
