### ISSUE TITLE
.cke_contents size after maximizing

### ISSUE THREAD

**Issue by treavis** [divio/djangocms-text-ckeditor#298]
After maximizing the window .cke_contents container overflows unpredictably, resulting in hidden content. Re sizing browser window fixes the problem. ( Javascript probably incorrectly calculates initial height value ).

Temporary hack in cms.ckeditor.css: .cke_contents { max-height: 87vh !important; }

**Comment by treavis** [comment]
There's also a similar problem with source editing window. When the content overflows, scroll bar is not visible. It's because source textarea gets css value from .cke_reset { box-sizing: content-box; } . Setting it to border-box seems to fix it.

Possible fix in cms.ckeditor.css: textarea.cke_source { box-sizing: border-box !important; }

**Comment by FinalAngel** [comment]
@treavis is this still a problem for you since the last release? If yes I'd welcome some screenshots and additional instructions on how to reproduce.

**Comment by treavis** [comment]
I have to disappoint you, but the problem still exists as of version 3.3. After editor window had been maximized the scrolling breaks and part of the content becomes hidden.

Screenshot taken from the demo of django-cms.
![screen1](https://cloud.githubusercontent.com/assets/7849374/15926917/30cf7500-2e47-11e6-80b7-2f7bf1b56422.png)
![screen2](https://cloud.githubusercontent.com/assets/7849374/15926923/345a9b96-2e47-11e6-9e92-6c8068d6bcb1.png)

**Comment by FinalAngel** [comment]
@treavis no worries, thanks for clarifying. @vxsx is that something you can fix?
