### ISSUE TITLE
there should be a way to add styles to the default stylesSet

### ISSUE THREAD

**Issue by alesdotio** [divio/djangocms-text-ckeditor#3]
setting stylesSet replaces all styles. it would be nice to be able to add style to default ones. (also the style option should be added to the 'CMS' toolbar)

docs: http://docs.cksource.com/ckeditor_api/symbols/CKEDITOR.stylesSet.html

these are my settings:

```
CKEDITOR_SETTINGS = {
    'language': '{{ language }}',
    'toolbar': 'Full',
    'skin': 'moono',
    'stylesSet': [
        {'name': 'MY SPECIAL STYLE' , 'element': 'h3', 'styles': {'color': 'Blue'}}
    ],
}
```

**Comment by Clindbergh** [comment]
Any solution to this?

https://github.com/divio/djangocms-text-ckeditor/blob/master/README.rst#inline-preview and #360  mentions the use of a javascript file, but I haven't been successful using the setting along with the js file it with this content

```
  CKEDITOR.stylesSet.add('my_custom_style', [
    { name: 'My Custom Block', element: 'h3', styles: { color: 'blue'} },
    { name: 'My Custom Inline', element: 'span', attributes: {'class': 'mine'} }
  ]);
```

No js error nor a python error, the file seems to be blatantly ignored.

**Comment by vxsx** [comment]
@Clindbergh you should use `default` instead of `my_custom_style`.

**Comment by Clindbergh** [comment]
@vxsx Thank you, but the file `/home/user/project/project/static/js/ckeditor.wysiwyg.js` seems to be ignored, do I have to include it somewhere so it will be loaded?

Using the variable `stylesSet` in `settings.py` as suggested will work but replaces existing styles (as noted by the original author). I vote for reopening this.

**Comment by vxsx** [comment]
It has to be in your static directory and the path should start from the root of the project. 
So for this example:

https://github.com/divio/django-cms-demo/blob/7a104acaa749c52a8ed4870a74898e38daf20e46/src/settings.py#L318-L324

the file is in `/home/mysuser/myprojectroot/static/js/addons/ckeditor.wysiwyg.js`

**Comment by Clindbergh** [comment]
Great, thank you! This works when I copy paste the default styles as well, so `/home/mysuser/myprojectroot/static/js/addons/ckeditor.wysiwyg.js` has to be

```
CKEDITOR.stylesSet.add('default', [
/*
*
* Default styles located at 
* https://github.com/divio/djangocms-text-ckeditor/blob/master/djangocms_text_ckeditor/static/djangocms_text_ckeditor/ckeditor/styles.js 
* pasted here
*
*/,
  { name: 'My Custom Block', element: 'h3', styles: { color: 'blue'} },
  { name: 'My Custom Inline', element: 'span', attributes: {'class': 'mine'} }
]
```
(and `CKEDITOR_SETTINGS = {
    'stylesSet': 'default:/static/js/addons/ckeditor.wysiwyg.js'
}` in `settings.py`)
