### ISSUE TITLE
Can't upload Image with an upload Button

### ISSUE THREAD

**Issue by madEng84** [divio/djangocms-text-ckeditor#307]
My question is: why don't you use the same widget from django-ckeditor (currently on 5.0.3 version) instead of creating a new one?

I had this error (it's not an error but I can't upload image with an upload button in the Image widget on ckeditor sidebar) either forcing my custom field using django-ckeditor's CKEditorWidget rendering the form in the admin interface. But I think it's not a good idea to modify get_editor_widget forcing to use django-ckeditor's CKEditorWidget  in cms_plugins.py because it expects other data.
The solution in that case was to use CKEditorUploadingWidget instead of CKEditorWidget.
I think that package is a good solution and can be use outside CMS too without modifying a model field declaration if you want to use in your model.

In my case i resolved this issue creating my own cms_plugin rendering the content with CKEditorUploadingWidget

Best Regards
![schermata 2016-03-15 alle 17 51 25](https://cloud.githubusercontent.com/assets/2088831/13786182/cecf2c82-ead6-11e5-9801-79b83a850b13.png)
![schermata 2016-03-15 alle 17 51 19](https://cloud.githubusercontent.com/assets/2088831/13786183/ced16b1e-ead6-11e5-93ac-9c660cc5579d.png)

**Comment by FinalAngel** [comment]
@madEng84 the reason here is connected with django-filer. We store the images there and should rather connect CKEditor with Filer directly. I agree that we can make this better and improve the UI for it. I'll connect this ticket with https://github.com/divio/djangocms-text-ckeditor/issues/285
