### ISSUE TITLE
$(...).autoSuggest is not a function ckeditor.js

### ISSUE THREAD

**Issue by jesusjl** [divio/djangocms-text-ckeditor#309]
Hi

ckeditor does not show on djangocms-blog plugin from nephila. Im currently on a complex project and not able to debug the problem. The same settings in another simpler project with just django-cms 3.1.2 and djangocms-blog works nice...

$(...).autoSuggest is not a function ckeditor.js
Uncaught TypeError: Cannot read property 'icons' of null

Please help

**Comment by FinalAngel** [comment]
hello @jesusjl and sorry for the late response. Auto suggest is not part of the core ckeditor plugin and added via djangocms-blog (taggit_autosuggest). Please open an issue on https://github.com/nephila/djangocms-blog

**Comment by jesusjl** [comment]
Thank you FinalAngel
