### ISSUE TITLE
Editor is not WYSIWYG

### ISSUE THREAD

**Issue by farooqaaa** [divio/djangocms-text-ckeditor#315]
For some reason, my TextPlugin editors are no longer WYSIWYG. All I see a "textarea" field called "body" and it shows the HTML code of the selected placeholder. Is this because of some recent update?

![ckeditor](https://cloud.githubusercontent.com/assets/930117/14761238/d40a526a-0973-11e6-88fe-904fdf1ce13e.png)

**Comment by FinalAngel** [comment]
@farooqaaa thanks for the report, do you have additional information on how your project is setup? What method did you use, which CMS Version is installed, a pip freeze can also help a lot.

**Comment by farooqaaa** [comment]
My project uses the regular method for setting up the plugin. Here's a pip freeze:

```
cmsplugin-filer==1.0.1
Django==1.9.5
django-appconf==1.0.1
django-classy-tags==0.7.2
django-cms==3.2.3
django-daterange-filter==1.1.1
django-filer==1.1.1
django-formtools==1.0
django-ipware==1.1.5
django-mptt==0.8.3
django-pipeline==1.6.8
django-polymorphic==0.8.1
django-sekizai==0.9.0
django-treebeard==4.0
djangocms-admin-style==1.1.0
djangocms-forms==0.1.16
djangocms-googlemap==0.4.0
djangocms-style==1.7.0
djangocms-text-ckeditor==2.9.1
easy-thumbnails==2.3
googlemaps==2.4.3
hashids==1.1.0
html5lib==0.9999999
isodate==0.5.4
jsonfield==1.0.3
Pillow==3.2.0
ply==3.8
psycopg2==2.6.1
pytz==2016.4
requests==2.9.1
six==1.10.0
slimit==0.8.1
stripe==1.32.2
tablib==0.11.2
Unidecode==0.4.19
```

**Comment by FinalAngel** [comment]
@divio/django-cms-core any idea what might be going on?

**Comment by mkoistinen** [comment]
@farooqaaa are you using the release of 3.2.3 from PyPI or latest from this repository?

**Comment by cyberstar** [comment]
@farooqaaa hi! can you please also check if you have any JS errors on this page? I had similar issue but that issue was related to other package that produced a JS error.

**Comment by farooqaaa** [comment]
@cyberstar Thank you. It was a javascript issue. The jquery-ui URL was dead.
