### ISSUE TITLE
'cmsplugins' needs to work for djangocms_text_ckeditor.fields.HTMLField

### ISSUE THREAD

**Issue by macolo** [divio/djangocms-text-ckeditor#317]
Currently djangocms-text-ckeditor's `HTMLField` doesn't have the ability to link to other CMS pages.

DjangoCMS has `cmsplugins`, a plugin for CKeditor for that. 

However as explained in `djangocms-text-ckeditor`'s README (see `Usage as a model field`), this is not supported for HTML fields. This Model Field is heavily relied upon for the creation of custom content elements in DjangoCMS. Not being able to link to CMS pages from them is quite a brutal shortcoming of DjangoCMS in comparison to other CMS systems and frameworks.

Can we have some insights into why this core piece of functionality is not implemented in djangocms-text-ckeditor?

**Comment by yakky** [comment]
This functionality depends on the whole django CMS placeholder stack, which is not available unless you are using a placeholder (a ``PlaceholderField`` in the case of non CMS models)
You can easily add a ``PlaceholderField`` in you custom models as detailed in http://django-cms.readthedocs.io/en/latest/how_to/placeholders.html and then using plugins all the way down.
You can provide your users a default text plugin when the model is created first to make their work easier as detailed in the ``default_plugins`` section of the ``CMS_PLACEHOLDER_CONF`` documentation (http://django-cms.readthedocs.io/en/latest/reference/configuration.html#cms-placeholder-conf)

**Comment by macolo** [comment]
Quick note: Workaround for something like 'Title and Text" plugin which contains a text input and a html field: Create a plugin that contains an input field and let editors know that they should insert a TextPlugin into it (`allow_children = True`)

**Comment by macolo** [comment]
Update: the django CMS Association's ckeditor 5 workgroup is working on making the link functionality independent from the in-text plugin functionality. This means that the problem described in this issue would be solved for the linking functionality, i.e. it would be possible to link dynamically to CMS pages even inside djangocms_text_ckeditor.fields.HTMLField.

Please read more and/or participate here: https://django-cmsworkspace.slack.com/archives/C01CJN3DSNS

**Comment by Aiky30** [comment]
With regards to placeholder functionality, django cms v4 allows other models to reuse the placeholder model, there could be a way to make djangocms-text-ckeditor work using a placeholder of it's own. This is how djangocms-alias works. This would be for django-cms 4+ only though sadly.
