### ISSUE TITLE
edit table is not possible

### ISSUE THREAD

**Issue by lory87** [divio/djangocms-text-ckeditor#321]
If I add a table to the ckeditor plugin it breaks when I want to edit the table

This issue can be reproduced with cms 3.2.5

![screen shot 2016-05-31 at 16 22 31](https://cloud.githubusercontent.com/assets/2270884/15677786/0c07b248-274c-11e6-8082-c70d4b5a1d68.png)

**Comment by FinalAngel** [comment]
@lory87 I don't have this issue: http://d.pr/v/IX6X I can add content and change properties without any problems. Does the issue still persist on CMS 3.3?

**Comment by vxsx** [comment]
Should be fixed with 3.3
