### ISSUE TITLE
Adding plugins doesn't work in CMS v.3

### ISSUE THREAD

**Issue by tunarob** [divio/djangocms-text-ckeditor#33]
When I try to add any plugin, for example snippet or link I get error:

> There was an error creating the plugin.

In the console I see:

> http://localhost:8000/admin/cms/page/edit-plugin/12/add-plugin/ 404 (NOT FOUND) 

Adding that plugins (link, picture, ...) directly to placeholder works fine. I have all migrations, INSTALLED_APPS filled etc.

Any ideas why it's not working?

**Comment by lukasz-virtualo** [comment]
problem reappears in 2.8.0. solved only by downgrading to 2.6.0

**Comment by kerkeslager** [comment]
Is there any word on this? Like lukasz-virtualo, I'm seeing this in 2.9.1 and had to downgrade. 2.7.1 seems to be the highest version that doesn't have the issue.

**Comment by vxsx** [comment]
@lukasz-virtualo @kerkeslager 

> Warning
>
> For django CMS 3.0 and 3.1 use djangocms-text-ckeditor <= 2.7 (e.g.: version 2.7.0).
> For django CMS 2.3 and 2.4 use the djangocms-text-ckeditor 1.x releases (e.g.: version 1.0.10).
> For Django 1.4 and 1.5 use djangocms-text-ckeditor < 2.7.
> cms.plugins.text and djangocms-text-ckeditor can't be used at the same time.

https://github.com/divio/djangocms-text-ckeditor/blob/1a6734f31ec8c837906d19ce95ceb59004988add/README.rst
