### ISSUE TITLE
Manipulating plugin proxies in the text field can yield illegitimate plugins

### ISSUE THREAD

**Issue by mkoistinen** [divio/djangocms-text-ckeditor#330]
This is a known issue, but I've created this issue so that we can refer to it from other repos.

**Comment by jsma** [comment]
Is this resolved by the new inline preview system? This was also discussed in https://github.com/divio/djangocms-link/issues/59

**Comment by FinalAngel** [comment]
@jsma don't really understand what this issue is referring too, the issue related to djangocms-link is the editing behaviour. What CKEditor now does is, render the plugin as an internal widget and then open the admin changeform. Maybe you could help me describe the issue?

**Comment by jsma** [comment]
@FinalAngel, both https://github.com/divio/cmsplugin-filer/issues/179 (which @mkoistinen closed in favor of this issue) and https://github.com/divio/djangocms-link/issues/59 detail issues when double-clicking links in CKEditor which resulted in corrupted content and/or plugins. These both appear to be resolved now that the previewing system is in place. @mkoistinen, did you have other related issues you were tracking here that aren't yet resolved?

**Comment by FinalAngel** [comment]
@jsma thanks for clarifying, let's wait for @mkoistinen response.

**Comment by vxsx** [comment]
Should be resolved, feel free to reopen if not.
