### ISSUE TITLE
Double-clicking to edit a newly created plugin may result in edit form for wrong plugin

### ISSUE THREAD

**Issue by mkoistinen** [divio/djangocms-text-ckeditor#331]
(Copied from @darbula's Issue https://github.com/divio/cmsplugin-filer/issues/178):

This bug is very easy to reproduce:

In text editor write link1, select and add new CMSPlugin > Filer Link let it link to www.foo.com

Add new paragraph, write link2, select and add new CMSPlugin > Filer Link and let it link to www.bar.com

Double click link1 and editor is populated with Name: link2 and Url www.foo.com.

**Comment by vxsx** [comment]
This is no longer an issue with latest versions
