### ISSUE TITLE
sanitizer import error due to changes in html5lib

### ISSUE THREAD

**Issue by saeed-222** [divio/djangocms-text-ckeditor#336]
I get the following import error when using djangocms-text-ckeditor with html5lib 0.999999999 installed. Please not that I did not specified any specific version for html5lib and it has been installed by default.
```
 File "....../lib/python3.4/site-packages/djangocms_text_ckeditor/models.py", line 13, in <module>
    from .html import clean_html, extract_images
  File "...../lib/python3.4/site-packages/djangocms_text_ckeditor/html.py", line 8, in <module>

    from html5lib import sanitizer, serializer, treebuilders, treewalkers
ImportError: cannot import name 'sanitizer'
```

See also release notes for html5lib Released on July 14, 2016: [https://pypi.python.org/pypi/html5lib](https://pypi.python.org/pypi/html5lib)

**Comment by czpython** [comment]
@saeed-222 Thanks. We've released a new version of djangocms-text-ckeditor that pins the html5lib version to < 0.999999999.

**Comment by jedie** [comment]
Ran into the same problem :(

New release not on PyPi, yet?!?

**Comment by saeed-222** [comment]
I don't think that a temporarily work-a-round would solve this issue, Adding support for new changes will be a better idea.

**Comment by czpython** [comment]
Pinning html5lib version to < 0.999999999 is perfectly fine as long as other apps don't require a higher version. I agree that adding support for html5lib >= 0.999999999 would be better but there's only so much we can do each time a new dependency is released.

In the meantime, we've removed html5lib as a dependency from django-cms 3.3.x and will backport to 3.2.x

**Comment by czpython** [comment]
Just for the sake of clarity, what I meant with "there's only so much we can do" is that we're focusing all our efforts on finishing the long term release of djangoCMS. That's the only reason why we've pinned the html5lib version.

We would really appreciate if someone has the time to contribute a backwards compatible patch that adds compatibility with the latest html5lib.

**Comment by Chronial** [comment]
> We would really appreciate if someone has the time to contribute a backwards compatible patch that adds compatibility with the latest html5lib.

Is it essential that it is backwards compatible? This adds a lot of complexity and the old implementation seems dangerous anyways, since it modifies global settings of html5lib: https://github.com/divio/djangocms-text-ckeditor/blob/6e0b6c2fb48984ee579cc3ca672b5064af1bf10d/djangocms_text_ckeditor/html.py#L23

**Comment by rando305** [comment]
It sure would be good if you guys fixed this.  Pinning it to .9x7 deosn't  help when other packages require .9x9

**Comment by jvamvas** [comment]
@czpython Would it be possible to re-open this issue or to create another issue for the html5lib version problem? I'm afraid it might slip off the project's radar otherwise.

**Comment by czpython** [comment]
Thanks for the follow up, created ticket #403

**Comment by DanielTate** [comment]
This seems to be an issue still with the new Django-cms update

**Comment by czpython** [comment]
Hello,
This issue is tracked in #403, the cms is decoupled from this app so it won't affect this issue.
