### ISSUE TITLE
Using `replace` instead of `split` and `join`.

### ISSUE THREAD

**Issue by vstoykov** [divio/djangocms-text-ckeditor#339]
When I looked at how djangocms-text-ckeditor passes settings to the template was confused about this line https://github.com/divio/djangocms-text-ckeditor/blob/3.0.1/djangocms_text_ckeditor/widgets.py#L73

```
'settings': language.join(json.dumps(configuration).split("{{ language }}")),
```

It needed to put a debugger there to inspect and see what is going on in order to understand what this line was doing. At the end I realized that the purpose of this is to replace `{{ language }}` with current language.

Isn't this the same as:

```
'settings': json.dumps(configuration).replace("{{ language }}", language)),
```

Or there is something that I'm missing?

**Comment by vThaian** [comment]
https://github.com/divio/djangocms-text-ckeditor/blob/3.7.0/djangocms_text_ckeditor/widgets.py#L98
`3.7.0` using `{{ language }}` as you suggested. So, I'm closing this PR. Thanks for your contribution @vstoykov.
