### ISSUE TITLE
Add support for html5lib>=0.9999999 since django-cms requires it

### ISSUE THREAD

**Issue by saeed-222** [divio/djangocms-text-ckeditor#340]
Django-cms release 3.3.0 or higher requires `html5lib>=0.9999999`. And since `djangocms-text-ckeditor` does not support html5lib new changes right now, Using `djangocms-text-ckeditor` as one of installed app, It is not possible to upgrade django-cms to version 3.3.0 or higher.

**Comment by saeed-222** [comment]
See also https://github.com/divio/djangocms-text-ckeditor/issues/336

**Comment by czpython** [comment]
html5lib is no longer a dependency of django-cms and djangocms-text-ckeditor has pinned the html5lib version to be less than the latest 9999
