### ISSUE TITLE
Version 2.9.4 is broken in django 1.8+

### ISSUE THREAD

**Issue by yakky** [divio/djangocms-text-ckeditor#342]
Apparently djangocms-text-ckeditor 2.9.4 has been released from 2.7.x branch and the 2.9.x branch has been deleted

**Comment by czpython** [comment]
@yakky Was there a 2.9.x branch? I don't recall there being one, also can't find it locally.

**Comment by yakky** [comment]
Uhm I thought that before releasing 3.0 a 2.9.x would have been created. But anyway the point is that 2.9.4 is really 2.7.x something and we must release a 2.9.5 as 2.9.3 + htmllib pinning. I can do that if that's ok for you

**Comment by czpython** [comment]
@yakky Got it. Sounds good, thanks.

**Comment by yakky** [comment]
@czpython please check 1594dc71e94d0b58eaf7c28f043310a0273bd8a4 I pushed on top of 2.x branch because fixing the 2.x would result in impossible to read pull request
If looks good to you (tests are all green) I'll release 2.9.5 later on pypi

**Comment by czpython** [comment]
LGTM. Thanks!

**Comment by yakky** [comment]
Fixed by 2.9.5 release
