### ISSUE TITLE
Upgrade to 3.0.1 problem

### ISSUE THREAD

**Issue by davidmaxs** [divio/djangocms-text-ckeditor#343]
Hi, after Upgrade and migrate django cms from 3.0 to 3.2 i have big problem with cmsplugion_filer__image in djangocms-text-ckeditor .  In all page with image in djangocms-text-ckeditor i get Unknown column 'cmsplugin_filer_image_filerimage.thumbnail_option_id' in 'field list. 

django-cms==3.3.1
djangocms-text-ckeditor==3.0.1
cmsplugin-filer==1.1.2
django-filer==1.2.4

**Comment by czpython** [comment]
Hello @davidmaxs,
Closing this as it was likely an issue with the cmsplugin-filer app.
