### ISSUE TITLE
Document that cmswidget needs to be in extraPlugins setting

### ISSUE THREAD

**Issue by stefanw** [divio/djangocms-text-ckeditor#349]
For my installation, I had customised the `extraPlugins` setting and did not have "cmswidget" in there (and it used to worked).

With the latest version `3.1.0`, when I opened a Text plugin, [this line in plugins.js](https://github.com/divio/djangocms-text-ckeditor/blob/master/djangocms_text_ckeditor/static/djangocms_text_ckeditor/ckeditor_plugins/cmsplugins/plugin.js#L446) throws an error:

```js
// Uncaught TypeError: Cannot set property 'inline' of undefined
that.editor.widgets.registered.cmswidget.inline = true;
```

`that.editor.widgets.registered` does not contain `cmswidget`.

I had to add 'cmswidget' in the list of extraPlugins to make this work. This doesn't seem to be documented. Having a list of required "extraPlugins" for djangocms-text-ckeditor to work might be a good idea.

**Comment by czpython** [comment]
Fixed by https://github.com/divio/djangocms-text-ckeditor/pull/355

**Comment by vxsx** [comment]
Will be properly fixed by https://github.com/divio/djangocms-text-ckeditor/pull/361
