### ISSUE TITLE
3.1.0 inline preview not working for some django-filer images

### ISSUE THREAD

**Issue by jsma** [divio/djangocms-text-ckeditor#353]
I have a page which has three instances of cmsplugin-filer image plugins on it. After upgrading to djangocms-text-ckeditor 3.1.0, only the first two can be double-clicked to edit (they both show the yellow border on hover and a blue border when single-clicked). 

For the third image plugin instance, there is no border shown on hover or on single click. If I double-click the image, the editor becomes disabled, no clicks or scrolling possible within the editor (the minimize/maximize/'x' to close and the Cancel/Delete/Save buttons are the only things that still work):

<img width="847" alt="screen shot 2016-08-26 at 4 11 38 pm" src="https://cloud.githubusercontent.com/assets/24574/18022890/e0e9c1a0-6ba7-11e6-9151-3498f58636a5.png">

The only difference between the plugins is that the third image plugin instance uses the 'file link' option to link the image to a cmsplugin-filer file.

If I click the 'Source' button in the editor, the rendered markup for the third plugin is broken:

	<cms-plugin alt="Image - test.png " id="11854" render-plugin="true" title="Image - test.png"></cms-plugin>

	<p>&nbsp;</p>

	<figure id="image_plugin_700"><a href="/media/filer_public/81/fa/81fa62ff-51aa-4bf0-891c-223f6cc54768/test.pdf" target="_blank"><img alt="test.png" class="img-responsive" src="/media/filer_public_thumbnails/filer_public/24/fb/24fb47ed-203d-4402-8904-90825f4cb116/test.png__726x941_q85_crop_subsampling-2_upscale.png" /></a></figure>

Note that the `<cms-plugin>` tag closed itself without wrapping the `<figure>` tag and an empty `<p>` was added.

**Comment by czpython** [comment]
Hello @jsma,
Can you post the full source of the text plugin?
I think that the <cms-plugin> tag shown there belongs to the second plugin and somehow that third one didn't get wrapped in a <cms-plugin> tag.

**Comment by jsma** [comment]
Actually the first two are wrapped (I've anonymized file names & alt text etc but left the markup as-is):

	<h3>&nbsp;</h3>
	<cms-plugin alt="Image - demo9.png " id="11494" render-plugin="true" title="Image - demo9.png">
	<figure id="image_plugin_286"><a href="https://www.example.com/" target="_blank"><img alt="demo9.png" class="img-responsive" src="/media/filer_public_thumbnails/filer_public/44/12/44125b11-eac5-4195-9395-9b7f12215617/demo9.png__1000x702_q85_crop_subsampling-2_upscale.png" title="demo9" /></a>

	<figcaption>course demo</figcaption>
	</figure>
	</cms-plugin>

	<h3>&nbsp;</h3>
	<cms-plugin alt="Image - demo1.png " id="11495" render-plugin="true" title="Image - demo1.png">
	<figure id="image_plugin_285"><a href="https://www.example.com/" target="_blank"><img alt="demo1.png" class="img-responsive" src="/media/filer_public_thumbnails/filer_public/65/13/65130804-8f3e-4460-8603-13bbf332199b/demo1.png__1000x700_q85_crop_subsampling-2_upscale.png" title="demo1" /></a>

	<figcaption>course demo</figcaption>
	</figure>
	</cms-plugin>

	<h3>Some kind of heading:</h3>

	<p>&nbsp;</p>
	<cms-plugin alt="Image - test.png " id="11854" render-plugin="true" title="Image - Online Curriculum.PNG"></cms-plugin>

	<p>&nbsp;</p>

	<figure id="image_plugin_700"><a href="/media/filer_public/81/fa/81fa62ff-51aa-4bf0-891c-223f6cc54768/test.pdf" target="_blank"><img alt="test.png" class="img-responsive" src="/media/filer_public_thumbnails/filer_public/24/fb/24fb47ed-203d-4402-8904-90825f4cb116/test.png__726x941_q85_crop_subsampling-2_upscale.png" /></a></figure>

**Comment by czpython** [comment]
I see, I've not seen the <figure> tag on ckeditor before, is that a custom plugin? 
The tag <figure id="image_plugin_700"> points to a plugin with id 700 while the <cms-plugin alt="Image - test.png " id="11854" tag points to 11854 which leads me to believe they're not the same plugin and somehow this <figure id="image_plugin_700"> was not migrated.

Was the third plugin editable before upgrading? Do you have a backup of this specific plugin's text before upgrading?

**Comment by jsma** [comment]
Sorry for the confusion/distraction, but you can ignore the `id="image_plugin_700"`, that's just the id of the underlying image instance which was added for reasons we won't go into here and hopefully aren't relevant. 

The `<figure>` tag is just coming from an overridden template for the standard cmsplugin-filer image plugin. I've created a [gist](https://gist.github.com/jsma/379a82e125f1eb23a5cb01d2be0ef620) of the actual template we're using. Again, hopefully not relevant.

To answer your question, yes, all three plugins are editable on the live site (I'm testing the upgrade of this plugin locally first). Here's what the 'Source' button reveals on the live site which is running version 3.0.1 of this plugin:

    <h3><img alt="Image" id="plugin_obj_11494" src="https://media.example.com/filer_public_thumbnails/filer_public/44/12/44125b11-eac5-4195-9395-9b7f12215617/demo9.png__1000x702_q85_crop_subsampling-2_upscale.png" title="Image - demo9.png" /></h3>

    <h3><img alt="Image" id="plugin_obj_11495" src="https://media.example.com/filer_public_thumbnails/filer_public/65/13/65130804-8f3e-4460-8603-13bbf332199b/demo1.png__1000x700_q85_crop_subsampling-2_upscale.png" title="Image - demo1.png" /></h3>

    <h3>Some kind of heading:</h3>

    <p><img alt="Image" id="plugin_obj_11854" src="https://media.example.com/filer_public_thumbnails/filer_public/24/fb/24fb47ed-203d-4402-8904-90825f4cb116/test.png__726x941_q85_crop_subsampling-2_upscale.png" title="Image - test.png" /></p>

I'm not at all up to speed on the changes that made inline previews possible. All three plugins use the same template shown in the gist. The first two instances link to external urls and have captions, whereas the third plugin links to a file and doesn't have a caption. So the mystery to me is why would it create a `<cms-plugin>` tag that doesn't enclose the rendered output of the plugin?

**Comment by czpython** [comment]
Thanks for the information @jsma

Let's break this into parts:

1. When upgrading to ckeditor with real preview, a migration runs to convert all stored `<img plugin_id_x>` tags to their `<cms-plugin>` equivalent. Can you verify directly in the database that all from this plugin has been correctly converted to use the new tags? (Maybe post the text to create a trail with any sensitive data hidden ofc)
2. After upgrading, when you edit the text plugin, an ajax call will fire for every `<cms-plugin>` tag found inside the text to fetch the plugin's rendered content and place it inside that plugin's `<cms-plugin>` tag. When you use the "Source" button, the markup you see has already been modified by these ajax calls. Based on the text you provided earlier, the error is already present at this stage as the `<cms-plugin>` tag belonging to the third plugin does not wrap it.

**Comment by jsma** [comment]
The problem seems to be that in 3.0.1, the plugin started its life as `<img alt="Image" id="plugin_obj_*"`, which CKEditor happily placed within a `<p>`. However, in 3.1.0 this img tag gets replaced by the real markup `<figure>`, which can't be nested in a `<p>` tag. Haven't yet traced where the modification is coming from, but when previewing, the source code gets rewritten, resulting in the broken preview markup first reported. 

It gets funnier: after saving the broken preview markup, we then end up with duplicate images. The reason is that the `<figure>` remains outside the `<cms-plugin>` tag in the markup, but on save, the `<cms-plugin>` gets rendered again. That is, the broken markup:

    <p>&nbsp;</p>
    <cms-plugin alt="Image - test.png " id="11854" render-plugin="true" title="Image - Online Curriculum.PNG"></cms-plugin>

    <p>&nbsp;</p>

    <figure id="image_plugin_700"><a href="/media/filer_public/81/fa/81fa62ff-51aa-4bf0-891c-223f6cc54768/test.pdf" target="_blank"><img alt="test.png" class="img-responsive" src="/media/filer_public_thumbnails/filer_public/24/fb/24fb47ed-203d-4402-8904-90825f4cb116/test.png__726x941_q85_crop_subsampling-2_upscale.png" /></a></figure>

Gets turned into this:

    <p>&nbsp;</p>
    <cms-plugin alt="Image - test.png " id="11854" render-plugin="true" title="Image - Online Curriculum.PNG">
        <figure id="image_plugin_700"><a href="/media/filer_public/81/fa/81fa62ff-51aa-4bf0-891c-223f6cc54768/test.pdf" target="_blank"><img alt="test.png" class="img-responsive" src="/media/filer_public_thumbnails/filer_public/24/fb/24fb47ed-203d-4402-8904-90825f4cb116/test.png__726x941_q85_crop_subsampling-2_upscale.png" /></a></figure>
    </cms-plugin>

    <p>&nbsp;</p>

    <figure id="image_plugin_700"><a href="/media/filer_public/81/fa/81fa62ff-51aa-4bf0-891c-223f6cc54768/test.pdf" target="_blank"><img alt="test.png" class="img-responsive" src="/media/filer_public_thumbnails/filer_public/24/fb/24fb47ed-203d-4402-8904-90825f4cb116/test.png__726x941_q85_crop_subsampling-2_upscale.png" /></a></figure>

Should also note, that if I try to create a new instance of an image plugin, it works as it should. The `<figure>` gets wrapped in the `<cms-plugin>` tag, with no extraneous `<p>` tags involved. 

I suppose I can blame djangocms-text-ckeditor's old way of doing things for creating a situation where CKEditor would incorrectly wrap our plugin template with `<p>` tags. But I'm not sure if there's anything for djangocms-text-ckeditor to do about it now. Is this worth putting a warning in the upgrade docs? This would potentially affect other plugins which insert markup which can't be contained in `<p></p>`. 

The only 'solution' I can think of for myself is to write a script to make sure that no image plugin instances are wrapped in a `<p>` tag.

**Comment by vxsx** [comment]
This is indeed one of the problems we were trying to solve with the new inline preview system - get rid of invalid markup. The unwrapping of the `<p><cms-plugin><figure>` is happening in the browser itself, and when you save it breaks in a way you described. 

What we could do is to check if there is a block level element inside of the plugin markup and based on that - unwrap the `<p>` tags ourselves. We just have to do it before the browser comes into play. I have to check if it's possible.

**Comment by vxsx** [comment]
@jsma could you try reproducing with https://github.com/divio/djangocms-text-ckeditor/pull/358 ?

**Comment by jsma** [comment]
@vxsx there are some major issues with this. A site was inadvertently upgraded to 3.2.0 and is now essentially bricked. No existing plugins are editable. 

If we erase all plugins from a page and attempt to add brand new plugins, it actually inserts the old `<img alt="Image" id="plugin_obj_11494"` syntax but when we click the plugins in the editor, we get 404 errors when it tries to load the plugin pop-up (e.g. /admin/cms/page/edit-plugin/13262/). So we can't edit these plugins either.

In fact, it doesn't even use our image plugin template at all when rendering for the end user, it's literally showing non-logged in users the `<img alt="Image" id="plugin_obj_11494"> tag`.

We haven't been able to fully debug all the issues going on (which appear to be several) but we have one page that literally only had a cmsplugin-filer image plugin which in turn linked to a filer file instance. We wanted to test erasing the existing embedded plugins. However, if we try to save this page with the text editor completely empty, it still shows the old plugin. The only way to make the old plugin 'disappear' is if we put in some placeholder text and save that. So we go back to the now empty text editor, attempt to add the image plugin but get the old syntax. Save and publish and the end user gets the image served via the old syntax.

And yes, we've cleared both browser and server-side caching, collect static, etc etc.

On a 'minor' note, it's also adding `<p>&nbsp;</p>` everywhere so when you save a page, it is now full of unnecessary whitespace.

This is pretty dangerous stuff. We can't downgrade, if we do all their plugins will disappear from every page. 

How thoroughly has the new inline preview functionality been tested in real-world conditions?

**Comment by czpython** [comment]
@jsma 
Hey, so you're currently on 3.2.0 ckeditor and adding a new plugin results in the old `<img alt="Image" id="plugin_obj_11494">` syntax?

**Comment by jsma** [comment]
There appears to be a bug in plugins.js when using Safari:

<img width="907" alt="screen shot 2016-09-10 at 4 09 29 pm" src="https://cloud.githubusercontent.com/assets/24574/18414041/057865f6-7771-11e6-9ee7-623c29af5fe5.png">

We haven't debugged the root cause yet, but posting here in case someone else is able to figure it out first.

It appears we can actually edit the site using Chrome, so that's good news! However, we're still seeing the oddity of it generating a lot of pointless `<p>&nbsp;</p>` tags. We go into source, clean them up, hit save, open the editor and they're back.

**Comment by jsma** [comment]
@czpython yes, in production environment using Safari, if we attempt to add a new cmsplugin-filer-image instance, it renders as the old syntax both for editors and end users. This does not happen with Chrome using the same production environment.

**Comment by vxsx** [comment]
@jsma it looks like you're getting cached old ckeditor javascript for some reason. if you see the image tag with plugin_obj_xxx id - it's definitely created by the older version of it. New version creates `<cms-plugin>` markup instead. you said you've cleaned the cache, but i've seen it on one of our production sites and only going to the chrome settings and removing cached files for last month actually helped

i think if you compare the files served in safari and in chrome you would confirm it

completely emptying text plugin is impossible, plugin contents can't be empty (should just delete a plugin in that case), so space of empty `<p></p>` can be used for clearing

Caching issues should be fixed with https://github.com/divio/djangocms-text-ckeditor/pull/361 in place

i'd love to hear more more about the extra `<p>` tags. Are they appearing around the image plugin you mentioned in original post or everywhere?

**Comment by jsma** [comment]
Thanks @vxsx! 

Manually clearing the browser cache did seem to resolve the issue. I had seen `?t=G4CD` appended to urls so mistakenly assumed cache-busting was already in place. Should have taken a deep breath and looked more closely at what the browser was doing.

However, it may be tricky to get everyone with CMS access to clear the browser cache in every browser they have (at work, home, phone, etc) so hoping #361 is the answer. Is there a point release for PyPI in the works for this feature or should we pip install via git for now?

As far as the extra `<p>` tags, it appears to be inserting them between `<cms-plugin>` tags as well as between any legitimate `<p>` tag which contains a link plugin `<cms-plugin>`.

If I delete them in the source view, click save, then double-click to reopen the editor and go to the source view again, they are back.

This only happens on pages that have embedded plugins. A plain text plugin instance with no other plugins does not generate the extra `<p>` tags at all. I also have one page that only has a single image plugin instance and no other markup...this page also does not generate any `<p>` tags. Is the javascript doing clever stuff when the markup is more complicated?

Here's a simplified version of a page where we're consistently seeing this behavior:

    <h3>Sub-head</h3>
    <cms-plugin> {{ plugin goes here}}
    </cms-plugin>

    <p>&nbsp;</p>
    <cms-plugin>{{ plugin goes here }}
    </cms-plugin>

    <p>&nbsp;</p>

    <h3>Next sub-head</h3>

    <p>&nbsp;</p>
    <cms-plugin>{{ plugin goes here }}
    </cms-plugin>

    <p>&nbsp;</p>

    <p>Paragraph with no plugins or inner HTML markup.</p>

    <p>&nbsp;</p>

    <p>Paragraph with a link plugin <cms-plugin alt="Link - here " id="11835" render-plugin="true" title="Link - here"> <a href="/example/">here</a></cms-plugin>.</p>

    <p>&nbsp;</p>

    ...

**Comment by vxsx** [comment]
Not yet @jsma, but i think we definitely should do a point release asap, wdyt @czpython ?

Regarding `<p>` tags, could you post the markup of the plugin that is used in `{{ plugin goes here }}`?

In https://github.com/divio/djangocms-text-ckeditor/pull/358 I added the logic for unwrapping the the plugins that are both block-level and wrapped with a `p`. That should definitely not affect the link plugin though

**Comment by vxsx** [comment]
Actually nevermind, I see the weird behaviour with adding lots of `<p>&nbsp;</p>` :(

**Comment by vxsx** [comment]
https://github.com/divio/djangocms-text-ckeditor/pull/367 this one should fix the problem with the extra `<p>` tags

**Comment by jsma** [comment]
This appears to have fixed all the issues I reported. Thanks for your help and work on this!
