### ISSUE TITLE
JS issue when using TextEditorWidget/HTMLField outside CMS

### ISSUE THREAD

**Issue by yakky** [divio/djangocms-text-ckeditor#354]
When using TextEditorWidget or HTMLField outside the CMS (i.e.: in normal models as rich text editor) the following JS error is returned:
``plugin.js Uncaught TypeError: Cannot set property 'inline' of undefined`` @ https://github.com/divio/djangocms-text-ckeditor/blob/master/djangocms_text_ckeditor/static/djangocms_text_ckeditor/ckeditor_plugins/cmsplugins/plugin.js#L455

Apparently cmsplugins plugin does not check if it's a CMS environment during initialization

Tested on django CMS 3.3.2
djangocms-text-ckeditor 3.0.1 is ok

**Comment by czpython** [comment]
Thanks @yakky.
We'll try to tackle this by monday morning.

**Comment by yakky** [comment]
To clarify have a look at the following custom configurations: https://gist.github.com/yakky/f35119aeaf37e07832b0c91633553d6b

using the top one, the admin will work correctly, but in the text plugin there is no cmsplugin dropdown
using the bottom one, text plugin is ok but the opening the normal model return a js error in console. If the ckeditor configuration loads more plugins afterward, the ckeditor will not load due to the error
