### ISSUE TITLE
stylesSet and contentCss

### ISSUE THREAD

**Issue by vxsx** [divio/djangocms-text-ckeditor#360]
At the moment the only way to specify correct styles and config inside of ckeditor is to hardcode the paths to  them like this:

``` python
CKEDITOR_SETTINGS = {
    'stylesSet': 'default:/static/js/addons/ckeditor.wysiwyg.js',
    'contentsCss': ['/static/css/base.css'],
}
```

If you're using different place to store them, e.g. somewhere on s3 bucket or if you use hashed file names you will run into problems.

What we should do instead is to handle the given paths with `{% static %}` automatically

**Comment by vThaian** [comment]
@vxsx what is status with this?

**Comment by jrief** [comment]
@vxsx you can use `django.utils.text.format_lazy` to solve this.

In many of my projects I've added this line to my settings:

```
CKEDITOR_SETTINGS = {
    ...
    'stylesSet': format_lazy('default:{}', reverse_lazy('admin:cascade_texticon_wysiwig_config')),
    ...
}
```

by evaluating lazy, you can postpone the final resolution of your path.
