### ISSUE TITLE
get_plugins_from_text hardcoded plugin_type prevents extending TextPlugin

### ISSUE THREAD

**Issue by yakky** [divio/djangocms-text-ckeditor#363]
The hardcoded string at https://github.com/divio/djangocms-text-ckeditor/blob/master/djangocms_text_ckeditor/utils.py#L126 prevents extending ``TextPlugin`` with custom one.
It needs to be retrieved dynamically based on parent plugin

**Comment by czpython** [comment]
Thanks for reporting @yakky. Totally my fault.
The plugin_type check filter was more a precaution on my side, I'll remove it.
Should be fine as it was previous behavior to not filter by this.

**Comment by czpython** [comment]
Github should put the **Close and comment** far away from the **Comment** button 😞
