### ISSUE TITLE
Signature changes break djangocms-cascade's carousel plugin

### ISSUE THREAD

**Issue by mliudev** [divio/djangocms-text-ckeditor#373]
Signature change to `plugin_tags_to_user_html(...)` breaks carousel and probably other plugins that call this method. Link to issue: https://github.com/jrief/djangocms-cascade/issues/182.

Since this is a backwards incompatible change, semantic versioning suggests bumping the major version. I think this should at least be a minor version change.

**Comment by czpython** [comment]
Thanks for reporting @mliudev.
The initial signature change was introduced in 3.2.0 which was a minor version change from 3.1.0, also this function was never documented as a public API, thus we don't guarantee a deprecation period.

**Comment by mliudev** [comment]
Fair enough, although 3.2.0 still works with the carousel. The 3.2.0 method signature still accepts 3 arguments: https://github.com/divio/djangocms-text-ckeditor/blob/3.2.0/djangocms_text_ckeditor/utils.py#L84.
