### ISSUE TITLE
Django 1.10 compatibility

### ISSUE THREAD

**Issue by sailorsamoor** [divio/djangocms-text-ckeditor#381]
The plugin is forcing to install Django 1.9.*

**Comment by czpython** [comment]
Hi there,
Currently djangoCMS does not "officially" support Django 1.10 because one of our dependencies (django-treebeard) is not released with 1.10 support.

As a result, most apps in the djangoCMS ecosystem don't support 1.10 yet.
I'll keep the ticket open though, as it's something in our todo.

**Comment by sailorsamoor** [comment]
I'm sorry, I read the requirements - there are Django 1.9.
