### ISSUE TITLE
Style for adding a new plugin not right

### ISSUE THREAD

**Issue by mistalaba** [divio/djangocms-text-ckeditor#384]
Sorry for the vague subject. What I'm experiencing is better described with an image:
![add plugin](https://cloud.githubusercontent.com/assets/738293/19019663/4af3e9b2-88b9-11e6-8786-ef3c4870d248.jpg)

Basically, the iframe (or the parent div) doesn't cover the whole modal as it should (I guess). I've been disabling my own stylesheets just to make sure it's not a conflict there, and it doesn't change. Also tried for a while to edit the used styles with dev tools but it's too complexed for my uninitiated eye.

Any ideas?
I'm using:
Django==1.8.13
django-ckeditor==4.4.8
django-cms==3.3.2
djangocms-admin-style==1.2.4
djangocms-text-ckeditor==3.2.1

Let me kno what else you might need :)

Update: I just saw that it works fine in Chrome, this is apparently a FF issue.

**Comment by vxsx** [comment]
Hi @mistalaba, which version of Firefox do you see the problem in? also - are there any errors present in the console? 

So far I cannot reproduce on FF48 on mac / windows 10

**Comment by mistalaba** [comment]
The problem existed in FF 49, but after the upgrade to 49.0.1 it has disappeared. Might have been a caching thing, although I did hard refresh. Thanks for looking in to it!
