### ISSUE TITLE
Uncaught TypeError: Cannot read property 'trim' of undefined

### ISSUE THREAD

**Issue by vivazzi** [divio/djangocms-text-ckeditor#388]
I get this bug when I add my plugin to djangocms-text-ckeditor. This bug has shown when popup window of added plugin has shown and when has closed.
I tested on my project and aldryn demo online project - the same bugs.

**Comment by vThaian** [comment]
@vivazzi did you try a new version? I see that Vadim merged PR with a fix for this. I'm closing let me know if this not resolve your issue.

**Comment by vivazzi** [comment]
Yes, this bug was fixed a long time ago.
