### ISSUE TITLE
css files added to my plugin template don't add to render_plugin_preview.html

### ISSUE THREAD

**Issue by vivazzi** [divio/djangocms-text-ckeditor#389]
I try to use preview of my plugins in djangocms-text-ckeditor as like this:
![button](https://cloud.githubusercontent.com/assets/11954799/19212672/ba31f494-8d88-11e6-9463-dde19a05b0ee.png)
I fiound it at https://www.youtube.com/watch?v=zQIFVzy3DsM

But my styles which I added to template through sekizai templatetags:
```
{% load sekizai_tags %}

{% addtoblock 'css' %}<link rel="stylesheet" type="text/css" href="{{ STATIC_URL }}my_link/css/my_link.css" property="" />{% endaddtoblock %}

<span class="my_link">
    <a class="btn">
            {{ instance.get_title }}
    </a>
</span>
```
don't work. File `{{ STATIC_URL }}my_link/css/my_link.css` doesn't include to editor.

While I try to how do it I found `def _render_cms_plugin(plugin, context):` in  djangocms-text-ckeditor/utils.py. And I don't understand about:
```
# If I render the plugin without rendering a template first, then context processors
    # are not called and so plugins that rely on these like those using sekizai will error out.

    # The compromise is to render a template so that Django binds the context to it
    # and thus calls context processors AND render the plugin manually with the context
    # after it's been bound to a template.
```

How I can use my styles for plugins in ckeditor?

**Comment by vxsx** [comment]
There are certain limitations to the rendering of plugin previews inside of ckeditor - so sekizai won't work. 

What would work however, is specifying that stylesheet as 
```
CKEDITOR_SETTINGS = {
     'contentsCss': ['/path/to/base.css', '/path/to/my/link/plugin.css']
}
```

**Comment by vivazzi** [comment]
Thanks!
