### ISSUE TITLE
Additional template option

### ISSUE THREAD

**Issue by bhrutledge** [divio/djangocms-text-ckeditor#399]
It'd be nice to be able to configure additional templates to render the plugin contents, similar to djangocms-link and -picture. This would make it easier to add wrapper markup. I filed a [similar issue](https://github.com/divio/djangocms-style/issues/27) on djangocms-style.

**Comment by bhrutledge** [comment]
I'm again wishing that I could add wrapper markup around a Text plugin, without having to putting it inside a Style plugin. Any idea what the level of effort would be to add this?

**Comment by czpython** [comment]
Hello @bhrutledge,
I'm closing this as a won't fix.
The text plugin UI would be affected to add such option and so far we've not seen much demand/need for it.

You can override the text plugin template and add the wrapper there or you can also use the AbstractText class to create your own version of the text plugin.
