### ISSUE TITLE
Editor doesn't load properly after upgrading to 3.3.1 from 3.0.1

### ISSUE THREAD

**Issue by DanielKirov** [divio/djangocms-text-ckeditor#400]
I was using djangocms-text-ckeditor 3.0.1 and after upgrading to 3.3.1 when opening a text plugin instance it doesn't load the existing content or any buttons (basically CKEditor doesn't load.)

I can see the following errors in my console that are causing this:
![ckeditor_issue](https://cloud.githubusercontent.com/assets/2420136/20396645/c0948610-acde-11e6-911d-0f355361208a.png)

This is on Django 1.8.16 and django-cms 3.4.1

I couldn't find this issue mentioned anywhere else.
I've tried deleting browser cache/trying a different browser but to no avail.

**Comment by vxsx** [comment]
any chance you have `templates/cms/plugins/widgets/ckeditor.html` template in your project?
does it look different from https://github.com/divio/djangocms-text-ckeditor/blob/master/djangocms_text_ckeditor/templates/cms/plugins/widgets/ckeditor.html ?

**Comment by DanielKirov** [comment]
Ah, that is indeed the case. I had forgotten I had overwritten it in order to change the labels of a few bits. Everything seems to work now, thanks!
