### ISSUE TITLE
TextEditorWidget outside TextCKEditorPlugin

### ISSUE THREAD

**Issue by jrief** [divio/djangocms-text-ckeditor#401]
Until version 3.0 it was possible to use the ``TextEditorWidget`` outside of a TextCKEditorPlugin and to add the LinkPlugin inside the edited text area.

Since version 3.1 this is much more complicate. Is there a possibility to use a TextEditorWidget outside of a TextCKEditorPlugin *and* being able to add/edit other available CMS plugins?

**Comment by czpython** [comment]
Hello @jrief,
Are you referring to the 3.0 version of ckeditor or django CMS?

**Comment by jrief** [comment]
From version 3.1 through 3.4.
The widget without plugin works fine. Only the combination of text and a sub-plugin, such as a link doesn't work anymore.
My workaround is to use the provided field instead of the widget.

**Comment by jeroenpeters1986** [comment]
Hi @jrief, could you elaborate a little more on your workaround? I would like to use the djangocms-text-editor in one of my own custom plugins as well. I have another plugin which can display a product, but the cmsplugins-part of the HTMLField I use (from djangocms-text-editor) seems to be gone, also when it's `allow_children = True`.

**Comment by jrief** [comment]
@jeroenpeters1986 if you need a clean solution, add a `PlaceholderField` to your model. Then add a CKEditorWidget to that field and within, it is perfectly possible to add all text-enabled plugins you like.
The reason it doesn't work with the `HTMLField` is, that all plugins are part of a tree whose root is said placeholder.
