### ISSUE TITLE
HTMLserializer

### ISSUE THREAD

**Issue by rando305** [divio/djangocms-text-ckeditor#402]
html.py: line 63
    s = serializer.htmlserializer.HTMLSerializer(omit_optional_tags=False,
                                                 quote_attr_values=True)

needs to go to:
    s = serializer.HTMLSerializer(omit_optional_tags=False, quote_attr_values=True)
for the new version of html5lib.

**Comment by czpython** [comment]
Thanks for the suggestion @rando305, there's backwards compatibility to consider as well as some patches that are done in the library. Closing as a duplicate of https://github.com/divio/djangocms-text-ckeditor/issues/403
