### ISSUE TITLE
Subclassing Text or AbstractText

### ISSUE THREAD

**Issue by ursomniac** [divio/djangocms-text-ckeditor#404]
I'm writing an app that would like to use djangocms-text-editor but I need to add a field to the plugin.   I've tried subclassing from AbstractText but that sets things up such that the admin always assumes the user wants to create a new object;   subclassing from Text takes care of that, but then you lose the TextEditorWidget (you just get a TextField).

Am I missing something (sometimes my stupidity knows no bounds) or is the only way to make this work to hack the original code (Which I don't want to do for the obvious reasons)...   

(Now that I think of it - the same problem comes when you try to use Text as a child plugin too...)

**Comment by czpython** [comment]
@ursomniac 
Due to some limitations on the text plugin, anytime a user adds a text plugin it actually gets created instead of when the user presses save.
