### ISSUE TITLE
Inline icon is not showing in Editor window.

### ISSUE THREAD

**Issue by leety** [divio/djangocms-text-ckeditor#412]
Hi,

I am using Django CMS 3.4.2 with CKeditor 3.4.0.  When inserting either the Glyphicons or FontAwesome icons from CMS Plugins, the WYSIWYG editing window would not display the selected icon.  However, it would show in the page once the page is saved.

for example, inserting the gift icon the HTML code for the <cms-plugin> tag from the WYSIWYG editor shows:
`<cms-plugin data-cke-real-element-type="span" alt="Icon - fa-gift " id="62" render-plugin="true" title="Icon - fa-gift" data-cke-widget-data="%7B%22classes%22%3Anull%7D" data-cke-widget-upcasted="1" data-cke-widget-keep-attr="0" data-widget="cmswidget" class="cke_widget_element"></cms-plugin>`

However, for inline preview for images will show up correctly.  

I have searched the web but was unable to find others with similar issue.

**Comment by vxsx** [comment]
Hi,

I think this is an issue similar to https://github.com/aldryn/aldryn-bootstrap3/issues/112#issuecomment-265686941 - missing configuration

**Comment by leety** [comment]
Thanks for the reply, indeed it is the same issue, however, I have encountered another problem, please allow me to continue on the original thread.

**Comment by vxsx** [comment]
Good to know it helped. I'll leave this issue open until we document this
