### ISSUE TITLE
Failure to render subclasses of TextPlugin

### ISSUE THREAD

**Issue by jakob-o** [divio/djangocms-text-ckeditor#413]
Hi,

after an update we encountered an error which does prevent us from using child plugins within subclasses of TextPlugin. I tracked the error down to here:
https://github.com/divio/djangocms-text-ckeditor/blob/3.4.0/djangocms_text_ckeditor/cms_plugins.py#L481
The issue is that the queryset is explicitly filtered on the concrete base class. Removing the filter works but might result in a performance penalty...

Regards

Jakob

**Comment by czpython** [comment]
@jakob-o I remember this issue was fixed.. you're subclassing the plugin or the plugin model?

**Comment by jakob-o** [comment]
Hi,

I subclassed the plugin, __not__ the plugin model, this is why narrowing the plugin_type filter to "TextPlugin" excludes the plugin which is actually "RunningTextPlugin".

Regards

Jakob

**Comment by jakob-o** [comment]
Hi,

another possibility would be to correct the url from 
```
/admin/cms/page/plugin/text_plugin/render-plugin/
```
to
```
/admin/cms/page/plugin/<actual-class>/render-plugin/
```

Unfortunately I don't know where this URL is generated in the editor.

Regards

Jakob

**Comment by czpython** [comment]
Yeah that's why I was so confused.. `plugin_type` should point to `RunningTextPlugin` since we do `self.__class__.__name__` but if the url points to `text_plugin` then your class is never used.

**Comment by jakob-o** [comment]
Hey,

is this reproducible for you, or am I missing something?

Regards

Jakob

**Comment by czpython** [comment]
The problem is here https://github.com/divio/djangocms-text-ckeditor/blob/master/djangocms_text_ckeditor/cms_plugins.py#L324.

We shouldn't use self.model since multiple plugins can point to the same model.
Maybe we change it to:

```
plugin_type = self.__class__.__name__.lower()
url_name = "%s_%s_%s" % (self.model._meta.app_label, plugin_type, name)
```

which for you would return:

`djangocms_text_ckeditor_runningtextplugin_render_plugin`

**Comment by jakob-o** [comment]
Works for me. Thanks

**Comment by jakob-o** [comment]
Unfortunately this fails the tests...
