### ISSUE TITLE
'cmsplugins' option in Toolbar is empty

### ISSUE THREAD

**Issue by gmenih341** [divio/djangocms-text-ckeditor#419]
I'm trying to have an `HTMLField` that allows adding CMS Plugins, like the Default `Text` plugin offers. By my understanding, adding `cmsplugins` to the `toolbar_HTMLField` should do the trick, but it doesn't give me any plugins to pick form.

I get the dropdown, but it's empty. What am I doing wrong? Here's my configuration:

```python
CKEDITOR_SECTION_HEADING_CONF = {
    'enterMode': 2,
    'toolbar_HTMLField': [
        ['Bold', 'Italic', 'Underline', 'RemoveFormat', '-', 'BulletedList'],
        ['cmsplugins'],
        ['Link', 'Unlink'],
        ['Cut', 'Copy', 'Paste', 'PasteText', 'PasteFromWord', '-', 'Undo', 'Redo'],
        ['Source']
    ]
}
```

**Comment by vxsx** [comment]
> HTMLField that allows adding CMS Plugins

In short - this is not possible due to how django cms works with plugins, placeholders, pages etc.

**Comment by jedie** [comment]
I have exact the same question!

There is nothing about cmsplugins in the docs :(
