### ISSUE TITLE
Upgrade from 3.0.1 to 3.4.0: all djangocms-links broken

### ISSUE THREAD

**Issue by macolo** [divio/djangocms-text-ckeditor#420]
I am trying to upgrade from 3.0.1 to 3.4.0 but the upgrade breaks all links that have been created previous to the update.

This is how broken links look like on 3.4.0:

![image](https://cloud.githubusercontent.com/assets/4056979/23832890/0b495f5a-073e-11e7-9979-5f05e2636f0d.png)

this is what's left in the source code:

![image](https://cloud.githubusercontent.com/assets/4056979/23832898/2a3a449c-073e-11e7-837e-f2a98f0dfd35.png)

When I revert to 3.0.1 old links start working again.

When I create new links with 3.4.0 they work fine, alongside the broken old ones.

I wonder if this behaviour can be reproduced on other systems as well?

**Comment by vThaian** [comment]
I didn't check this on mentioned versions because we don't support that version already. Did you try with the newest version? If you have issues with that then please feel free to ping me and we will resolve your problem.

**Comment by macolo** [comment]
Not yet, will let you know should this happen as well when upgrading from 3.0.1 to an even newer version.
