### ISSUE TITLE
How to use it in a form?

### ISSUE THREAD

**Issue by Xosted** [divio/djangocms-text-ckeditor#423]
Hi,
I am sorry if this is not the right place to ask but I just couldn't figure out where to drop my question. I guess it must be simple but I couldn't find how to use this module outside of the admin creation of a page?
I would like to create a form, with a ckeditor powered textarea, for my visitors to use and submit.
What would be the prefered way to do this?
Sorry again if this isn't the right place.

**Comment by czpython** [comment]
Hello @Xosted,
You can use it like so:

```python
from djangocms_text_ckeditor.fields import HTMLFormField

class YourForm(forms.Form):
    content = HTMLFormField(required=False)
```

Hope that helps.
