### ISSUE TITLE
How to setup this settings CKEDITOR.dtd.$removeEmpty['i'] = false

### ISSUE THREAD

**Issue by rgcarrasqueira** [divio/djangocms-text-ckeditor#426]
Hello!

I would like to remove the feature that remove empty tags inside CKEDITOR, there is a way, but I have to change the JS config file that is not available directly at this plugin.

So I'd like to know how to setup this property using configuration available at this plugin using the django way?

Thanks

Rogério Carrasqueira

**Comment by vxsx** [comment]
Normally it's done in a way that's described in the readme - https://github.com/divio/djangocms-text-ckeditor#inline-preview

You would create the file with the ckeditor configuration, like https://github.com/divio/django-cms-explorer/blob/908a88afa4e1d1176e267e77eb5c61e31ef0f9e5/static/js/addons/ckeditor.wysiwyg.js#L73 and then add it to settings like here: https://github.com/divio/django-cms-demo/blob/7a104acaa749c52a8ed4870a74898e38daf20e46/src/settings.py#L318-L324
