### ISSUE TITLE
Race condition between popup show and its z-index setting when plugin/placeholder is clicked multiple times

### ISSUE THREAD

**Issue by petrklus** [divio/djangocms-text-ckeditor#429]
Steps to reproduce:

1. Add text plugin
2. Add link / other CMS plugin and save, then re-open the editor
3. Click rapidly on the newly created link - the popup can no longer be activated (in the demo, link "non" has been clicked multiple times in rapid succession).

No other popups can be activated until editor is closed and re-opened.

Demo of the bug in action:[https://www.youtube.com/watch?v=F278EmtY5ZI](https://www.youtube.com/watch?v=F278EmtY5ZI&feature=youtu.be)

What seems to be important is that the link/plugin being clicked is outside of the area where the popup is going to be created - i.e. if the link was to be obscured by the newly loaded popup, then multiple clicking does not make any difference. 

I could see that during that multiple clicking, the z-index of the dialog is not set correctly even when the dialog itself is created.

**Comment by petrklus** [comment]
@vxsx this is happening on 3.5, I've set up demo at https://ckeditor-bug-stage.us.aldryn.io/en/?edit

**Comment by petrklus** [comment]
@vxsx my guess would be an issue at https://github.com/divio/djangocms-text-ckeditor/blob/9ae390e7419d3be34615fb43d991f44da0f306cd/djangocms_text_ckeditor/static/djangocms_text_ckeditor/ckeditor_plugins/cmsdialog/plugin.js#L877 but will leave it to someone more familiar with the code to debunk

**Comment by petrklus** [comment]
or, more likely, issue here https://github.com/divio/djangocms-text-ckeditor/blob/9ae390e7419d3be34615fb43d991f44da0f306cd/djangocms_text_ckeditor/static/djangocms_text_ckeditor/ckeditor_plugins/cmsdialog/plugin.js#L888

**Comment by petrklus** [comment]
@vxsx @czpython is this something that looks like an easy fix for you guys? I've also been able to reproduce this on Divio demo site (running 3.4 judging based on the skin)

**Comment by vxsx** [comment]
it would be good to remove those dialog/resize plugins, but ckeditor doesn't support touch devices fully
it looks simple but it's not an easy fix. i'll take a look this week

**Comment by petrklus** [comment]
Thank you @vxsx - very much appreciated. From my simplistic point of view, wouldn't it be sufficient to always put in minimal z-index to ensure that dialog windows are never below the main text body?

**Comment by petrklus** [comment]
@vxsx hello, luck fixing this?

**Comment by petrklus** [comment]
@vxsx @czpython one more observation - this only seems to be an issue when the text editor is maximised. So probably some default min z-index is not reflecting the ckeditor current state?

**Comment by vxsx** [comment]
@petrklus sorry, not yet

**Comment by petrklus** [comment]
@vxsx @czpython Another observation - I believe that previous versions (not sure which one I was looking at but roughly at a time of Django CMS 3.2) put up an overlay when dialog is activated - which then prevents further clicking and this issue altogether.

Is it a regression or was the overlay intentionally removed?

**Comment by petrklus** [comment]
@vxsx Sorry to keep pestering you but can you please share if there is any plan to fix this one?

**Comment by petrklus** [comment]
@vxsx Sorry to keep pestering you but can you please share if there is any plan to fix this one? Also, I cannot see status of the bug as accepted, is there any reason this may not be considered a bug?

**Comment by vxsx** [comment]
@petrklus there is a plan to fix it, but other things have higher priority at the moment

**Comment by vxsx** [comment]
Should be fixed on latest master with #460
