### ISSUE TITLE
Link edit dialog malformed on certain text editor sizes

### ISSUE THREAD

**Issue by petrklus** [divio/djangocms-text-ckeditor#430]
When opening up editor to edit "link" type anchors, the editor dialog window is not sized correctly:

https://youtu.be/j9qAZpZSaFk

This seems to be happening mainly with standard link functionality (not CMS plugin links).

**Comment by petrklus** [comment]
@vxsx is this linked to https://github.com/divio/djangocms-text-ckeditor/issues/429 or is it a different issue?

**Comment by petrklus** [comment]
Looks like this has been reported in the ckeditor repository:

https://github.com/ckeditor/ckeditor-dev/issues/453

Just out of interest - how long does it usually take for a ckeditor fix to propagate to the Django CMS plugin?

**Comment by vxsx** [comment]
Normally few days, but it always depends on a lot of different things :)

**Comment by vThaian** [comment]
@petrklus new version of ckeditor resolved your problems?
