### ISSUE TITLE
Vulnerability scanning issue

### ISSUE THREAD

**Issue by sobolevn** [divio/djangocms-text-ckeditor#432]
We are using [`safety`](https://github.com/pyupio/safety) for our project to scan vulnerabilities.

It finds this:

> » safety check
> │ REPORT                                                                       │
> │ html5lib                   │ 0.9999999 │ <0.99999999              │ 25846    │
> 

Tried to upgrade `html5lib` to `0.999999999` (this version system is ridiculous!), but is not supported by this library.

**Comment by czpython** [comment]
Closing as duplicate of https://github.com/divio/djangocms-text-ckeditor/issues/403
