### ISSUE TITLE
Scrolling problem on mobile Android

### ISSUE THREAD

**Issue by jlucchese** [divio/djangocms-text-ckeditor#439]
The scrolling on mobile Android behaves buggy whenever I load a page that have a textarea with ckeditor. 

The problem appears to be with the way djangocms-text-ckeditor loads the ckeditor on a textarea (CMS.CKEditor.init). I test it with ckeditor and django-ckeditor and it behaved normally using CKEDITOR.replace.

To reproduce the problem:

1. Create an app with a ckeditor field
2. Load it up on a mobile device (I test it on a Moto X with Android)
3. Scroll up and down to check scrolling

**Comment by vThaian** [comment]
@jlucchese do you have still this issue? Could you please give me more details which versions of `django-cms`, `djangocms-text-ckeditor` and `django` do you use?

**Comment by jlucchese** [comment]
Hi @vThaian, I don't know what I did, but it seems to be working now.

I'm using:
django-cms 3.4.4
djangocms-text-ckeditor 3.5
django 1.8.18

**Comment by vThaian** [comment]
Good to hear that, @jlucchese. Let me close this right now. Feel free to reopen if you meet this issue again.
