### ISSUE TITLE
Code Snippet Plugin Disappears Upon Saving Text Content

### ISSUE THREAD

**Issue by artforlife** [divio/djangocms-text-ckeditor#453]
### Summary

I am not sure if this belongs here or is better suited for Aldryn NewsBlog repository. In short, placing a code snippet inside a Text content box does not work. 

I am able to place a Text box inside a `Newsblog_Article_Content` placeholder. Then, I type some text and place a CodeSnippet plugin inside the text content. The source looks like this:

```
<p>Post content here!</p>

<p>Some code here:<cms-plugin alt="Code - &lt;code&gt; " id="46" render-plugin="true" title="Code - &lt;code&gt;"><code>print(&#39;hello&#39;)</code></cms-plugin></p>
<cms-plugin alt="Code - &lt;pre&gt; " id="45" title="Code - &lt;pre&gt;"></cms-plugin>

<p>&nbsp;</p>
```
After I save the changes to the text, the code snippet is not shown. Upon opening the text area in edit mode, I see the following source:

```
<p>Post content here!</p>

<p>Some code here:<cms-plugin alt="Code - &lt;code&gt; " id="46" title="Code - &lt;code&gt;"></cms-plugin></p>

<p>&nbsp;</p>
```

* Python version: 3.5
* Django==1.10.9.dev20170906233227
* django CMS version: django-cms==3.4.5rc1

P.S. I have also experienced the same problem with Django 1.9 and a stack that seems to be deemed as "stable." I am just now reporting this because there were other more pressing issues at the time.

**Comment by vxsx** [comment]
Hi, thanks for reporting - which version of the djangocms-text-ckeditor is used?

**Comment by artforlife** [comment]
Is there a quick way to check that?

**Comment by vxsx** [comment]
Normally I check with something like `pip freeze | grep ckeditor`

**Comment by vxsx** [comment]
This issue might be similar to https://github.com/divio/djangocms-text-ckeditor/issues/454
Which "code" plugin are you using? If you have control over it - try removing html tags from it's __str__

**Comment by artforlife** [comment]
I am not using any code plugin I think. That is, I didnt install one on purpose. I will report on the version shortly.

**Comment by vThaian** [comment]
@artforlife any updates?

**Comment by artforlife** [comment]
@vThaian , I have not been playing with this issue. However, in the last few days I started building another site with DjangoCMS 3.6. I will keep an eye out for the same behavior. Feel free to close this, and I shall reopen if needed.
