### ISSUE TITLE
unwanted behavior - remove of empty tags (e.g.  <i class="fa fa-li></i>)

### ISSUE THREAD

**Issue by jankrnavek** [divio/djangocms-text-ckeditor#455]
Hello all,
ckeditor removes empty tags (e.g.   <i class="fa fa-li></i> )  and i dont want that behavior.
I want to set something like  
```
    $.each(CKEDITOR.dtd.$removeEmpty, function (i, value) {
            CKEDITOR.dtd.$removeEmpty[i] = 0;
        }); 
```
but dont know how to set  inside settings.py
Is there some solution?
Hanz

**Comment by vxsx** [comment]
You need to add a js configuration file in the settings (like here: https://github.com/divio/django-cms-demo/blob/7a104acaa749c52a8ed4870a74898e38daf20e46/src/settings.py#L322)

That file can contain what you want, normally we use something like this: https://github.com/divio/django-cms-explorer/blob/908a88afa4e1d1176e267e77eb5c61e31ef0f9e5/static/js/addons/ckeditor.wysiwyg.js#L73

Slighly more info here: https://github.com/divio/djangocms-text-ckeditor#inline-preview
