### ISSUE TITLE
Image Properties popup fails to appear in v3.5.1

### ISSUE THREAD

**Issue by dsummersl** [divio/djangocms-text-ckeditor#457]
Double clicking on an image in ckeditor region fails to bring up the "image properties" editor in version 3.5.1 and 3.5.2. Downgrading to v3.5.0 fixed the problem.

**Comment by dsummersl** [comment]
I looked at what was working in a firefox debug tool, then searched for the CSS class affected between the two releases, which suggests a z-index issue is at the root of the problem.

    git log 3.5.0..3.5.1 -G cke_dialog

Change: 7cad2b7

**Comment by vxsx** [comment]
Thanks for the report. It's not really clear to me why table properties dialog works correctly at the same time. But will fix soon

**Comment by db654** [comment]
Similar issue for me in 3.5.1 with the link modal though only when trying to edit existing links. When creating a new one, the dialog works correctly.

**Comment by vxsx** [comment]
@dsummersl @db654 could you try https://github.com/divio/djangocms-text-ckeditor/pull/460 and see if it fixes the problem for you?

**Comment by db654** [comment]
Yep, that fixes it for me. Thanks very much.
