### ISSUE TITLE
Can't save changes - Uncaught TypeError in browser console

### ISSUE THREAD

**Issue by creimers** [divio/djangocms-text-ckeditor#459]
`Django==1.8.18`
`django-cms==3.4.4`
`djangocms-text-ckeditor==3.5.1`

I have an instance of a TextPlugin containing text as well as multiple links and images. 

Upon saving changes in this instance, I get the following error in the browser console (tested both in Firefox and Chrome, latest versions at time of writing, respectively).

<img width="621" alt="bildschirmfoto 2018-01-23 um 10 39 09" src="https://user-images.githubusercontent.com/6090492/35269639-e57777b0-002c-11e8-9f3b-79a868b25f3a.png">

Subsequently, the spinner keeps spinning and nothing is saved. 

The same error also appears when the 'source code' button in the top right corner is clicked.

Do you have an idea what this could hint at? Corrupted markup?

Thanks!

**Comment by vxsx** [comment]
Hi @creimers - is it possible for you to provide the test project for this issue? Or an exact body of this particular text plugin at least? So far I wasn't able to reproduce

**Comment by vThaian** [comment]
@creimers ? We can't reproduce it now. Could you provide some test project with it for us?

**Comment by creimers** [comment]
Puh, I'm surprised to see that this is still open. As it is more than a year old, I'm inclined to just close it.
