### ISSUE TITLE
PyPI has 3.5.3 but CHANGELOG only describes versions through 3.5.1

### ISSUE THREAD

**Issue by trawick** [divio/djangocms-text-ckeditor#461]
Please document what changed so that your humble users can determine how urgently to apply the update :)  Thank you!

**Comment by czpython** [comment]
Thanks for reporting this.
We've addressed it in https://github.com/divio/djangocms-text-ckeditor/commit/4b0fc27a257fa5d51d5c4bc42529328382bf60f9
