### ISSUE TITLE
automatic generate "pasteFilter" ?!?

### ISSUE THREAD

**Issue by jedie** [divio/djangocms-text-ckeditor#466]
The CKEditor has the "pasteFilter": https://docs.ckeditor.com/ckeditor4/latest/api/CKEDITOR_config.html#cfg-pasteFilter

What's about to generate the tag list for it by **CKEDITOR_SETTINGS** ?

**Comment by vxsx** [comment]
This should be declared in settings on the project level.

**Comment by jedie** [comment]
It's about to generate this from existing settings and not add more not-DRY stuff ;)
