### ISSUE TITLE
[CKEDITOR.resourceManager.load] Resource name "cmswidget" was not found 

### ISSUE THREAD

**Issue by lwm** [divio/djangocms-text-ckeditor#471]
On django-cms==3.5.1 and djangocms-text-ckeditor==3.5.3 I see:

```
Loading failed for the <script> with source “http://127.0.0.1:8000/static/djangocms_text_ckeditor/ckeditor/plugins/cmswidget/plugin.js?t=H8DA”.
23:1
Loading failed for the <script> with source “http://127.0.0.1:8000/static/djangocms_text_ckeditor/ckeditor/plugins/cmsplugins/plugin.js?t=H8DA”.
23:1
Loading failed for the <script> with source “http://127.0.0.1:8000/static/djangocms_text_ckeditor/ckeditor/plugins/cmsresize/plugin.js?t=H8DA”.
23:1
Loading failed for the <script> with source “http://127.0.0.1:8000/static/djangocms_text_ckeditor/ckeditor/plugins/cmsdialog/plugin.js?t=H8DA”.
23:1
Error: [CKEDITOR.resourceManager.load] Resource name "cmswidget" was not found at "http://127.0.0.1:8000/static/djangocms_text_ckeditor/ckeditor/plugins/cmswidget/plugin.js?t=H8DA".
```

Whenever I try to edit page content in the CMS menu.

**Comment by lwm** [comment]
Oh, is django-cms 3.5.X supported? I saw https://github.com/divio/djangocms-text-ckeditor/commit/9b5d8d1ef5635ef66b9ed7d45bd8e0c56879d54d. It's not listed.

**Comment by lwm** [comment]
OK, the main error:

> Error: [CKEDITOR.resourceManager.load] Resource name "cmswidget" was not found at "http://127.0.0.1:8000/static/djangocms_text_ckeditor/ckeditor/plugins/cmswidget/plugin.js?t=H8DA".

I checked my local deployment. I do **not** have a `ckeditor/plugins/cmswidget/plugin.js` in my static folder. I **do** have a `ckeditor_plugins/cmsplugins/plugin.js`. Looks like some path wrangling went wrong somewhere.

**Comment by vxsx** [comment]
Hi, ckeditor shouldn't try to load them as they are bundled already (e.g. in https://github.com/divio/djangocms-text-ckeditor/blob/master/djangocms_text_ckeditor/static/djangocms_text_ckeditor/js/dist/bundle-8e5431f90c.cms.ckeditor.min.js#L1252)

Could you show your `CKEDITOR_SETTINGS` variable? 
Also - any chance you have the widget template in your project templates folder? (this one https://github.com/divio/djangocms-text-ckeditor/blob/master/djangocms_text_ckeditor/templates/cms/plugins/widgets/ckeditor.html)

**Comment by lwm** [comment]
Ah, I see. Well, let's see, I have this:

```
CKEDITOR_SETTINGS = {
        'toolbar': [
            [
                'Bold',
                'Italic',
                '-',
                'Format',
                'BulletedList',
                'NumberedList',
                '-',
                'Blockquote',
                'Cut',
                'Copy',
                'Paste',
                'PasteFromWord',
                'RemoveFormat',
                'Source',
                '-',
                'Link',
                'Unlink',
                '-',
                'Undo',
                'Redo',
                '-',
                "Table"
            ],
        ],
        'width': 700,
        'height': 400,
        'toolbarCanCollapse': False
}
```

**Comment by lwm** [comment]
Ah! Removing the `widgets` folder solved it! So, this is already bundled or?

I suppose this should be added for upgrade notes? Can submit a patch if needed!

**Comment by lwm** [comment]
Will close off for now, thanks for the help!

**Comment by vxsx** [comment]
The templates and static files are normally collected via standard django mechanism, so unless you explicitly override them i'd recommend not to keep them in the project itself.
