### ISSUE TITLE
link overlay problem

### ISSUE THREAD

**Issue by wfehr** [divio/djangocms-text-ckeditor#473]
First of all: I don't know if this issue belongs here or somewhere else. If not, I am sorry:)

I am using version 3.5.1 of the editor.

When you add a link (link-button, not a cmsplugin) and double-click it, the overlay has some errors:
- chrome: after closing the "link-layer" the overlay doesn't close
- firefox: the overlay is in front of the "link-layer"

If you click the link and either press "Ctrl+L", click the link-button or rightclick and select "edit link" everything works fine.

**Comment by vxsx** [comment]
Could you try reproducing the error on latest master?

**Comment by wfehr** [comment]
Tested the latest release (3.5.3) and the latest master.
On 3.5.3 it is still not working, but the latest master just works fine.

**Comment by vxsx** [comment]
Good. 3.6.0 will be released soonish
