### ISSUE TITLE
Some CKEditor plugins are pinned to old version

### ISSUE THREAD

**Issue by jrief** [divio/djangocms-text-ckeditor#475]
In version 3.5.3, **djangocms-text-ckeditor** switched from CKEditor version 4.6.2 to 4.7.3. However, many (presumably unused) plugins shipped with CKEditor have not been updated in the local source tree. This is rather confusing and may cause incompatibility errors.

Therefore, either remove those plugins, so that they have to be installed manually, or upgrade to a compatible version.

**Comment by jrief** [comment]
OK. I compared the versions on GitHub, for instance 
https://github.com/divio/djangocms-text-ckeditor/tree/master/djangocms_text_ckeditor/static/djangocms_text_ckeditor/ckeditor/plugins/image
against
https://github.com/ckeditor/ckeditor-dev/tree/release/4.7.x/plugins/image

and they differ. This of course because the distributed version is compiled.

However, wouldn't it be safer, instead of re-distributing code which has already been packaged, ship  **djangocms-text-ckeditor** with a `package.json` file and use `npm install` to install these kind of 3rd party dependencies. With the wide availability of `npm`, this nowadays seems to be common practice.

**Comment by vxsx** [comment]
I see your point, but I've tried that once and it didn't work very well. Main problems were that even if we are to bundle the released version of the `ckeditor` package - ckeditor uses it's own module loader that lazy loads some additional things on demand. To do that the files have to be static collected, so at the time it was a no go.

**Comment by jrief** [comment]
fixed in #534
