### ISSUE TITLE
 Document the text_enabled param for plugins

### ISSUE THREAD

**Issue by czpython** [divio/djangocms-text-ckeditor#478]
> I think the Django CMS docs could use a little more information about the `text_enabled` attribute, which is available on CMSPlugins.
> 
> It's a very cool attribute/setting, but it took me quite some time to find out that I was looking for this when I was developing a plugin for my work.

Reported by @jeroenpeters1986 in https://github.com/divio/django-cms/issues/6342

**Comment by vThaian** [comment]
I'm closing because PR with more info about `text_enabled` was merged.
