### ISSUE TITLE
html5lib-0.9999999

### ISSUE THREAD

**Issue by rando305** [divio/djangocms-text-ckeditor#485]
Installing djangocms-text-ckeditor-3.6.0 forces downgrading of html5lib to 0.9999999.  
I have other applications that require html5 lib to be at 1.0.1
Is there a plan to not keep this frozen where it is?

I'm not sure why this is a new issue.  It has been around a while.

**Comment by czpython** [comment]
Fixed by https://github.com/divio/djangocms-text-ckeditor/commit/175a1a444de8ca1ba4742196cb83150d45b5c505
