### ISSUE TITLE
CSRF verification failed. Request aborted. on image upload ( Django=2.1.7, djangocms-text-ckeditor>=3.7 )

### ISSUE THREAD

**Issue by Saurabh-Singh-00** [divio/djangocms-text-ckeditor#503]
When trying to upload image from the upload tab the csrf verification fails.

![image](https://user-images.githubusercontent.com/36993159/57194954-a3648080-6f6a-11e9-9498-1f051e90f394.png)

![image](https://user-images.githubusercontent.com/36993159/57194914-289b6580-6f6a-11e9-84aa-43b433d9839b.png)

![image](https://user-images.githubusercontent.com/36993159/57194934-74e6a580-6f6a-11e9-957a-99411dcb514d.png)

**Comment by agajankush** [comment]
Hey Saurabh were you able to fix this issue?

**Comment by Saurabh-Singh-00** [comment]
@agajankush I just dropped the idea of using ckeditor, did it using custom forms and ajax. If you face similar issue please feel free to file a issue and reference this.
