### ISSUE TITLE
400 (Bad Request error) while adding a plugin

### ISSUE THREAD

**Issue by robertweglarek** [divio/djangocms-text-ckeditor#51]
Having set for example:
```python
LANGUAGE_CODE = 'pl'
LANGUAGES = [
    ('pl', ugettext('Polski')),
]
```
there is an 400 - Bad request error while adding a plugin in editor. Adding plugins through a placeholder works fine.
Response from that configuration is:
```bash
Request URL:http://localhost:8000/admin/cms/page/add-plugin/
Request Method:POST
Status Code:400 BAD REQUEST
FORM DATA:
placeholder_id:30
plugin_type:LinkPlugin
parent_id:37
plugin_language:en
RESPONSE CONTENT:
Język musi być ustawiony na jeden z dostępnych!
```
plugin_language:en is a strange thing here, as my settings are set to PL.

Changing settings to works fine:
```python
LANGUAGE_CODE = 'en'
LANGUAGES = [
    ('en', ugettext('English')),
]
```

So the bug occurs when there is no EN language.
Detailed conversation about that bug is also [here](https://github.com/divio/djangocms-text-ckeditor/pull/35).

**Comment by FinalAngel** [comment]
Closed as the discussion in https://github.com/divio/djangocms-text-ckeditor/pull/35 has been resolved
