### ISSUE TITLE
HTMLField not working in custom plugin

### ISSUE THREAD

**Issue by michaelbird1155** [divio/djangocms-text-ckeditor#522]
Using the HTMLField in a custom plugin raises the error: 

    TypeError: from_db_value() missing 1 required positional argument: 'context'

Changing the from_db_value method to the below definition fixes the issue.

    def from_db_value(self, value, expression, connection, context=None):

**Comment by rsalmaso** [comment]
See https://github.com/divio/djangocms-text-ckeditor/pull/510

**Comment by michaelbird1155** [comment]
Ah thanks! I must have got too excited with djangocms release yesterday adding support for Django 3. http://docs.django-cms.org/en/latest/upgrade/3.7.2.html

**Comment by pupattan** [comment]
This issue blocks to upgrade to 3.7.2 for me.

**Comment by remoover** [comment]
Please help i have SAME ISSUE !!!! PLEASE URGENT !!! Many thanks for help !!!

**Comment by alvaromlg** [comment]
Looks like is fixed on this commit https://github.com/divio/djangocms-text-ckeditor/commit/48fc9522f612d41e70d6a844fd53dd1026318654

**Comment by yakky** [comment]
@alvaromlg correct
It's been fixed in 3.9.1
Closing the issue
