### ISSUE TITLE
Deprecation warning due to invalid escape sequences

### ISSUE THREAD

**Issue by tirkarthi** [divio/djangocms-text-ckeditor#524]
Deprecation warnings are raised due to invalid escape sequences. This can be fixed by using raw strings or escaping the literals. pyupgrade also helps in automatic conversion : https://github.com/asottile/pyupgrade/ . With noqa I guess this is intentionally ignored but given that it's raising deprecation warning it will be good to fix it.

```
find . -iname '*.py' | grep -Ev 'test.py' | xargs -P4 -I{} python3.8 -Wall -m py_compile {}
./tests/test_plugin.py:118: DeprecationWarning: invalid escape sequence \d
  return re.findall('\d+', url)[0]  # noqa
```

**Comment by yakky** [comment]
Fixed by #535
