### ISSUE TITLE
Inserting image plugin with filer into the editor results in a broken image icon, not the image

### ISSUE THREAD

**Issue by feczo** [divio/djangocms-text-ckeditor#57]
the image is visible both in filer when selecting and in the CMS window as well after saving the contents of the editor, 
but not in the editor (as attached broken image icon) the html code is inserted as below 

```
<p><img alt="FilerImagePlugin" id="plugin_obj_22" src="/static/ckeditor_plugins/cmsplugins/icons/FilerImagePlugin.png" 
title="FilerImagePlugin" /></p>
```
using cms 3.0 beta2 and djangocms-text-ckeditor==2.0.0
it is both in FF 22 and Chrome 28.0.1500.71

![screen shot 2013-07-31 at 3 44 23 am](https://f.cloud.github.com/assets/3347261/880671/fe4f7e0c-f93f-11e2-883e-4c30986b97bd.png)

**Comment by FinalAngel** [comment]
this has been resolved :)
