### ISSUE TITLE
Integration with django-filer for resizing copy/pasted pictures using the mouse in the editor

### ISSUE THREAD

**Issue by motiteux** [divio/djangocms-text-ckeditor#68]
This is an enhancement suggestion.
CKeditor allows to resize images using the mouse. However, the size to which it is uploaded to media using filer is the original one. 

It would be "nice" to have the size of the image to be recorded or the image to be resized automagically upon saving the plugin.

Thanks!

**Comment by FinalAngel** [comment]
closed in favour of #285
