### ISSUE TITLE
Allowing a shortcut or a button to save the plugin without closing it.

### ISSUE THREAD

**Issue by motiteux** [divio/djangocms-text-ckeditor#69]
Suggestion enhancement.

While editing on the page (using the toolbar for example), if someone wants to save his/her work, he/she has to click on the save button and the plugin is then closed. Which can be tedious if the save was just not to loose the current work.

Thanks!

**Comment by FinalAngel** [comment]
For this we have the "Save and continue editing" button. This is currently not possible inside the ckeditor. But we will be working on better positioning.
