### ISSUE TITLE
CMS PLugins button is missing

### ISSUE THREAD

**Issue by palmitoto** [divio/djangocms-text-ckeditor#72]
Hi, i need your help :-/

The cms Plugins disapear in the ckeditor.. any clue ??
![capture decran 2013-09-06 a 16 18 32](https://f.cloud.github.com/assets/966556/1096456/78935b2a-16ff-11e3-8a01-b775bc93e039.png)

**Comment by FinalAngel** [comment]
Closing as it has been documented
