### ISSUE TITLE
You do not have permission to edit a plugin

### ISSUE THREAD

**Issue by kainbacher** [divio/djangocms-text-ckeditor#78]
my usergroup dont have the permission to edit or add a text plugin.

for testing i added all permissions:

text | text | can add text
text | text | can change text
text | text | can delete text
## 

djangocms-text-ckeditor==1.0.10
Django==1.5.1
django-cms==2.4.2

**Comment by tarikki** [comment]
Any updates on this one? Ran into the same problem today. I _could_ give superuser permissions to the user (his personal webpage, wants to be able to update some sections without digging into any code) but he would probably appreciate a simpler layout with fewer options.
