### ISSUE TITLE
Mime error on drag/drop images in editor

### ISSUE THREAD

**Issue by brigantino2** [divio/djangocms-text-ckeditor#79]
When I to drag/drop an image inside the editor and save, I get an error, list index out of range, on this line of html.py > extract images

image_type = mime_type.split("/")[1]

since mime_type is an empty string. The src of the image dropped in the editor is something like this
data:;base64,/9j/4AAQSkZ....
as far as I've understood there should be a mime type in between : and ;

django 1.5.1
django-cms 3.0.0b2
djangocms-text-editor 2.0.2

**Comment by FinalAngel** [comment]
closed as it has been fixed but also considering #285
