### ISSUE TITLE
Shouldn't require django-cms

### ISSUE THREAD

**Issue by piquadrat** [divio/djangocms-text-ckeditor#97]
If you want to only use ``HTMLField`` without any CMS integration, you still have to install the CMS and configure all kinds of CMS-related settings. This could probably be solved by either turning imports from cms into "runtime" imports, or by carefully splitting up modules into ones depending on the cms and ones that do not.

**Comment by FinalAngel** [comment]
mentioned in #285 this package is mainly for django-cms, thus the name
